export type EventStatus =
  | "Featured"
  | "Live"
  | "Waitlist"
  | "Locked"
  | "Pending"
  | "Cancelled";

export type EventItem = {
  id: string;
  title: string;
  group: string;
  host: string;
  category: string;
  date: string;
  time: string;
  startsAt: string;
  location: string;
  suburb: string;
  distanceKm: number;
  lat: number;
  lng: number;
  price: string;
  attendees: number;
  capacity: number;
  image: string;
  imageAlt: string;
  description: string;
  tags: string[];
  lifeSignals: string[];
  fomo: string;
  status: EventStatus;
  booking: "Click-managed" | "External";
  relationshipGoal: string;
};

export type PeopleRecommendation = {
  id: string;
  name: string;
  initials: string;
  avatar?: string;
  neighborhood: string;
  intent: string;
  persona: string;
  bio: string;
  tags: string[];
  matchReason: string;
  nextEventId: string;
  accent: string;
};

/**
 * Curated portrait photos from Unsplash. Cycled deterministically by person id
 * so the same person always shows the same face. All images are 200x200,
 * face-cropped, and served via Unsplash's image CDN.
 */
const unsplashPortraits = [
  "1494790108377-be9c29b29330",
  "1500648767791-00dcc994a43e",
  "1438761681033-6461ffad8d80",
  "1517841905240-472988babdf9",
  "1531123897727-8f129e1688ce",
  "1506794778202-cad84cf45f1d",
  "1502823403499-6ccfcf4fb453",
  "1487412720507-e7ab37603c6f",
  "1539571696357-5a69c17a67c6",
  "1552058544-f2b08422138a",
  "1519085360753-af0119f7cbe7",
  "1521119989659-a83eee488004",
  "1534528741775-53994a69daeb",
  "1492562080023-ab3db95bfbce",
  "1463453091185-61582044d556",
  "1564564321837-a57b7070ac4f",
  "1546961342-091cbcb40d8d",
  "1504593811423-6dd665756598",
  "1513956589380-bad6acb9b9d4",
  "1573496359142-b8d87734a5a2",
];

function hashId(id: string) {
  let hash = 0;
  for (let i = 0; i < id.length; i++) {
    hash = (hash * 31 + id.charCodeAt(i)) >>> 0;
  }
  return hash;
}

export function avatarFor(person: { id: string; avatar?: string }) {
  if (person.avatar) return person.avatar;
  const photo = unsplashPortraits[hashId(person.id) % unsplashPortraits.length];
  return `https://images.unsplash.com/photo-${photo}?w=200&h=200&fit=crop&crop=faces&auto=format&q=80`;
}

export const navItems = [
  { label: "Discover", href: "/discover" },
  { label: "Events", href: "/events" },
  { label: "Dashboard", href: "/dashboard" },
  { label: "Merchant", href: "/merchant" },
  { label: "Admin", href: "/admin" },
];

export const animatedPrompts = [
  "I want to meet new friends in Newtown",
  "Find people for weekend coffee in Surry Hills",
  "I just moved to Marrickville and want a social group",
  "Show me low-pressure dinners in Bondi",
  "I want a fitness friend around Redfern",
  "Help me meet creative people in Glebe",
  "Find a walking group near Barangaroo",
  "I want to make friends in Parramatta",
];

export const starterPrompts = animatedPrompts.slice(0, 4);

export const categories = [
  "All",
  "Social",
  "Fitness",
  "Relationships",
  "Food",
  "Creative",
  "Career",
  "Community",
];

export const clickEvents: EventItem[] = [
  {
    id: "new-friends-barangaroo",
    title: "New Friends Picnic at Bondi",
    group: "Sydney First-Timers Social Club",
    host: "Maya Chen",
    category: "Social",
    date: "Fri, May 8",
    time: "6:30 PM",
    startsAt: "2026-05-08T18:30:00+10:00",
    location: "Bondi Pavilion",
    suburb: "Bondi Beach",
    distanceKm: 6.5,
    lat: -33.8913,
    lng: 151.2744,
    price: "Free",
    attendees: 47,
    capacity: 60,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "A hosted picnic for people who want easy conversation, shared snacks, and familiar faces for the next event.",
    tags: ["friends", "sydney", "new to town", "weekend", "low pressure"],
    lifeSignals: ["New to Town", "Ambivert", "Weekends"],
    fomo: "4 people you might Click with are already going.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Make two familiar faces before the next weekend.",
  },
  {
    id: "crossfit-coffee",
    title: "CrossFit Skills and Coffee Crew",
    group: "Inner West Fitness Mates",
    host: "Theo Morgan",
    category: "Fitness",
    date: "Sat, May 9",
    time: "8:00 AM",
    startsAt: "2026-05-09T08:00:00+10:00",
    location: "CrossFit Marrickville",
    suburb: "Marrickville",
    distanceKm: 6.7,
    lat: -33.91,
    lng: 151.1565,
    price: "$12",
    attendees: 24,
    capacity: 32,
    image: "/media/yoga.jpg",
    imageAlt: "People training together in a group fitness session",
    description:
      "Technique-focused partner drills, scalable workouts, and post-session coffee for people who want consistency without gym cliques.",
    tags: ["crossfit", "fitness", "training", "coffee", "accountability"],
    lifeSignals: ["Fitness-Focused", "Active", "Morning"],
    fomo: "Popular with people building a four-week fitness streak.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find a fitness partner for a four-week streak.",
  },
  {
    id: "slow-dating-six",
    title: "Slow Dating: Dinner Tables of Six",
    group: "Real Conversations Sydney",
    host: "Amelia Hart",
    category: "Relationships",
    date: "Thu, May 14",
    time: "7:00 PM",
    startsAt: "2026-05-14T19:00:00+10:00",
    location: "Petersham Bowling Club",
    suburb: "Petersham",
    distanceKm: 5.9,
    lat: -33.8954,
    lng: 151.1541,
    price: "$29",
    attendees: 40,
    capacity: 42,
    image: "/media/networking.jpg",
    imageAlt: "People talking at a warm hosted dinner event",
    description:
      "Hosted dinner tables where singles meet through small-group conversation first, with private mutual interest after the event.",
    tags: ["dating", "relationships", "dinner", "surry hills", "low pressure"],
    lifeSignals: ["Curious", "Ready", "Weeknights"],
    fomo: "Mostly relationship-minded guests who prefer small tables.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Meet people through conversation before matching.",
  },
  {
    id: "restaurant-table-eight",
    title: "Restaurant Meetup: Table for Eight",
    group: "Sydney Table Friends",
    host: "Lena Ortiz",
    category: "Food",
    date: "Fri, May 15",
    time: "7:00 PM",
    startsAt: "2026-05-15T19:00:00+10:00",
    location: "North Bondi Fish",
    suburb: "North Bondi",
    distanceKm: 7,
    lat: -33.8888,
    lng: 151.2814,
    price: "$38",
    attendees: 6,
    capacity: 8,
    image: "/media/networking.jpg",
    imageAlt: "People sharing food and conversation at a restaurant table",
    description:
      "A hosted restaurant table for people who want dinner plans without the awkward group-chat setup. Arrive solo, sit with eight, and let the host open the first conversation.",
    tags: ["restaurant", "dinner", "food", "new friends", "low pressure"],
    lifeSignals: ["New to Town", "Food", "Weeknights"],
    fomo: "Only two seats left at a small table designed for easy conversation.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Make dinner feel like the easiest first plan with new people.",
  },
  {
    id: "ordinary-creatives",
    title: "Creative Brunch for Ordinary People",
    group: "Ordinary People Making Things",
    host: "Noah Singh",
    category: "Creative",
    date: "Sun, May 17",
    time: "10:30 AM",
    startsAt: "2026-05-17T10:30:00+10:00",
    location: "The Courthouse Hotel",
    suburb: "Newtown",
    distanceKm: 4.2,
    lat: -33.8976,
    lng: 151.1793,
    price: "$18",
    attendees: 53,
    capacity: 70,
    image: "/media/concert.jpg",
    imageAlt: "Crowd at a warm local music and creative event",
    description:
      "A no-status brunch for writers, designers, builders, makers, and anyone who wants a recurring community around doing real things.",
    tags: ["creative", "brunch", "newtown", "friends", "community"],
    lifeSignals: ["Creative", "Weekend", "Curious Explorer"],
    fomo: "Strong overlap with makers, writers, and new locals.",
    status: "Featured",
    booking: "External",
    relationshipGoal: "Turn a hobby into a recurring group.",
  },
  {
    id: "career-walk",
    title: "Career Change Walk and Talk",
    group: "Sydney Career Switchers",
    host: "Priya Nair",
    category: "Career",
    date: "Wed, May 20",
    time: "6:00 PM",
    startsAt: "2026-05-20T18:00:00+10:00",
    location: "Bay Run, King George Park",
    suburb: "Lilyfield",
    distanceKm: 4.5,
    lat: -33.8681,
    lng: 151.1603,
    price: "Free",
    attendees: 31,
    capacity: 45,
    image: "/media/networking.jpg",
    imageAlt: "People talking at a community meetup",
    description:
      "A walking meetup for people changing careers, building confidence, and looking for peers rather than formal networking.",
    tags: ["career", "confidence", "walk", "networking", "support"],
    lifeSignals: ["Busy Professional", "Balanced", "Weeknights"],
    fomo: "Good fit for people rebuilding confidence around work.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Meet peers who understand the same career transition.",
  },
  {
    id: "dog-park-cleanup",
    title: "Dog Park Coffee and Cleanup",
    group: "Inner City Community Mates",
    host: "Jules Park",
    category: "Community",
    date: "Sat, May 23",
    time: "9:00 AM",
    startsAt: "2026-05-23T09:00:00+10:00",
    location: "Camperdown Memorial Rest Park",
    suburb: "Camperdown",
    distanceKm: 3.7,
    lat: -33.8902,
    lng: 151.1788,
    price: "Free",
    attendees: 18,
    capacity: 36,
    image: "/media/open-yoga.jpg",
    imageAlt: "Outdoor community group meeting in a park",
    description:
      "A light volunteer morning for pet owners, locals, and people who want a natural reason to talk while doing something useful.",
    tags: ["community", "pets", "coffee", "volunteering", "friends"],
    lifeSignals: ["Pet Owner", "Community", "Weekend"],
    fomo: "Popular with pet owners and people new to Camperdown.",
    status: "Locked",
    booking: "Click-managed",
    relationshipGoal: "Meet locals through a useful shared ritual.",
  },
  {
    id: "bondi-coastal-run",
    title: "Bondi Coastal Run and Smoothies",
    group: "Eastern Beaches Run Club",
    host: "Talia Brooks",
    category: "Fitness",
    date: "Sun, May 24",
    time: "7:30 AM",
    startsAt: "2026-05-24T07:30:00+10:00",
    location: "Bondi Icebergs Club",
    suburb: "Bondi Beach",
    distanceKm: 6.7,
    lat: -33.8915,
    lng: 151.2767,
    price: "Free",
    attendees: 34,
    capacity: 50,
    image: "/media/yoga.jpg",
    imageAlt: "People stretching before an outdoor fitness meetup",
    description:
      "A conversational coastal run for mixed paces, followed by smoothies and an easy stretch on the grass.",
    tags: ["running", "bondi", "fitness", "morning", "coffee"],
    lifeSignals: ["Morning", "Active", "Weekend"],
    fomo: "Popular with people who want fitness without a competitive vibe.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Find a familiar face for weekend movement.",
  },
  {
    id: "haymarket-dumpling-night",
    title: "Dumpling Night for New Locals",
    group: "Sydney Table Friends",
    host: "Grace Liu",
    category: "Food",
    date: "Mon, May 25",
    time: "6:45 PM",
    startsAt: "2026-05-25T18:45:00+10:00",
    location: "Din Tai Fung, Westfield Bondi Junction",
    suburb: "Bondi Junction",
    distanceKm: 4.5,
    lat: -33.8915,
    lng: 151.2503,
    price: "$22",
    attendees: 14,
    capacity: 18,
    image: "/media/networking.jpg",
    imageAlt: "People sharing casual food at a group table",
    description:
      "A small shared-table dinner where the host handles ordering, introductions, and keeping the conversation moving.",
    tags: ["dumplings", "dinner", "food", "new to town", "low pressure"],
    lifeSignals: ["New to Town", "Food", "Weeknights"],
    fomo: "A strong fit for people who want dinner plans after work.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Turn a simple dinner into a first Sydney circle.",
  },
  {
    id: "enmore-live-jazz",
    title: "Live Jazz at Enmore Back Room",
    group: "Late Set Listeners",
    host: "Marcus Bell",
    category: "Creative",
    date: "Tue, May 26",
    time: "8:00 PM",
    startsAt: "2026-05-26T20:00:00+10:00",
    location: "Enmore Theatre",
    suburb: "Enmore",
    distanceKm: 4.6,
    lat: -33.8977,
    lng: 151.174,
    price: "$18",
    attendees: 28,
    capacity: 40,
    image: "/media/concert.jpg",
    imageAlt: "Crowd listening to a small live music performance",
    description:
      "A hosted live jazz night for people who like music but do not want to arrive alone or force small talk.",
    tags: ["jazz", "live music", "enmore", "creative", "night"],
    lifeSignals: ["Music", "Weeknights", "Curious"],
    fomo: "Great overlap with music lovers and quieter creative people.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Make live music feel like a shared plan, not a solo errand.",
  },
  {
    id: "bronte-sunrise-yoga",
    title: "Bronte Sunrise Yoga and Tea",
    group: "Soft Start Sydney",
    host: "Elise Grant",
    category: "Fitness",
    date: "Wed, May 27",
    time: "6:30 AM",
    startsAt: "2026-05-27T06:30:00+10:00",
    location: "Bronte Beach Park",
    suburb: "Bronte",
    distanceKm: 6.3,
    lat: -33.9038,
    lng: 151.2635,
    price: "$15",
    attendees: 22,
    capacity: 30,
    image: "/media/yoga.jpg",
    imageAlt: "Outdoor group yoga session on grass",
    description:
      "Gentle yoga, warm tea, and a short intro circle before work. Designed for people easing back into social mornings.",
    tags: ["yoga", "wellness", "bronte", "morning", "low pressure"],
    lifeSignals: ["Morning", "Wellness", "Cautious"],
    fomo: "Most people come solo and leave with one familiar name.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Create a calm first meeting before the day gets busy.",
  },
  {
    id: "women-founder-breakfast",
    title: "Women Founders Breakfast Circle",
    group: "Sydney Career Switchers",
    host: "Mina Patel",
    category: "Career",
    date: "Thu, May 28",
    time: "8:00 AM",
    startsAt: "2026-05-28T08:00:00+10:00",
    location: "The Grounds of Alexandria",
    suburb: "Alexandria",
    distanceKm: 4.9,
    lat: -33.9109,
    lng: 151.1941,
    price: "$32",
    attendees: 19,
    capacity: 24,
    image: "/media/networking.jpg",
    imageAlt: "People networking over breakfast",
    description:
      "A practical founder breakfast for women building, freelancing, switching lanes, or wanting a sharper peer circle.",
    tags: ["career", "founders", "breakfast", "women", "networking"],
    lifeSignals: ["Busy Professional", "Morning", "Growth"],
    fomo: "Nearly full with people comparing real work problems, not pitches.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Make professional support feel candid and useful.",
  },
  {
    id: "kings-cross-community-kitchen",
    title: "Community Kitchen Prep Night",
    group: "Eastern Beaches Community Mates",
    host: "Samira Haddad",
    category: "Community",
    date: "Fri, May 29",
    time: "5:30 PM",
    startsAt: "2026-05-29T17:30:00+10:00",
    location: "Waverley Community Centre",
    suburb: "Waverley",
    distanceKm: 5.4,
    lat: -33.902,
    lng: 151.252,
    price: "Free",
    attendees: 26,
    capacity: 35,
    image: "/media/open-yoga.jpg",
    imageAlt: "Community volunteers gathering outdoors",
    description:
      "Prep meals with a small volunteer crew, then share tea afterward. A useful way to meet people without performative networking.",
    tags: ["volunteering", "community", "food", "kings cross", "friends"],
    lifeSignals: ["Community", "Weeknights", "Helpful"],
    fomo: "Good fit for people who prefer doing something useful while talking.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Meet good people through a practical shared task.",
  },
  {
    id: "alexandria-pottery-night",
    title: "After-Work Pottery Night",
    group: "Ordinary People Making Things",
    host: "Ruby Walsh",
    category: "Creative",
    date: "Sat, May 30",
    time: "4:00 PM",
    startsAt: "2026-05-30T16:00:00+10:00",
    location: "Clay Sydney Studio",
    suburb: "Alexandria",
    distanceKm: 4.7,
    lat: -33.9095,
    lng: 151.1948,
    price: "$45",
    attendees: 18,
    capacity: 22,
    image: "/media/concert.jpg",
    imageAlt: "Creative group event with warm lighting",
    description:
      "Beginner-friendly pottery with hosted table prompts, a snack break, and zero expectation that the bowl turns out straight.",
    tags: ["pottery", "creative", "alexandria", "weekend", "craft"],
    lifeSignals: ["Creative", "Weekend", "Curious"],
    fomo: "A favourite for people who want a task to make conversation easier.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Give people a shared object to laugh about and remember.",
  },
  {
    id: "glebe-trivia-teamup",
    title: "Glebe Trivia Team-Up",
    group: "Pub Quiz People",
    host: "Oscar Finch",
    category: "Social",
    date: "Sun, May 31",
    time: "6:00 PM",
    startsAt: "2026-05-31T18:00:00+10:00",
    location: "The Toxteth Hotel",
    suburb: "Glebe",
    distanceKm: 2.5,
    lat: -33.88,
    lng: 151.1856,
    price: "$8",
    attendees: 41,
    capacity: 48,
    image: "/media/networking.jpg",
    imageAlt: "People talking at a local social event",
    description:
      "Arrive solo and get placed on a friendly trivia team. The host rotates teams after round two so nobody is stuck.",
    tags: ["trivia", "pub", "friends", "glebe", "games"],
    lifeSignals: ["Social Adventurer", "Weekend", "Games"],
    fomo: "Works well for people who want instant team energy.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Make a group game do the first-conversation work.",
  },
  {
    id: "north-sydney-book-swap",
    title: "Sydney Park Book Swap Picnic",
    group: "Quiet Pages Club",
    host: "Hannah Reid",
    category: "Social",
    date: "Tue, Jun 2",
    time: "6:00 PM",
    startsAt: "2026-06-02T18:00:00+10:00",
    location: "Sydney Park",
    suburb: "St Peters",
    distanceKm: 5.1,
    lat: -33.9095,
    lng: 151.1842,
    price: "Free",
    attendees: 17,
    capacity: 28,
    image: "/media/open-yoga.jpg",
    imageAlt: "Relaxed outdoor social group sitting in a park",
    description:
      "Bring one book, swap stories about it, and join a low-key picnic for people who prefer quieter social plans.",
    tags: ["books", "picnic", "north sydney", "quiet", "friends"],
    lifeSignals: ["Introvert", "Weeknights", "Low Pressure"],
    fomo: "Designed for people who like a softer room and a reason to talk.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Let a favourite book introduce people for you.",
  },
  {
    id: "manly-snorkel-walk",
    title: "Clovelly Snorkel Walk and Chips",
    group: "Eastern Beaches Weekend Crew",
    host: "Ben Archer",
    category: "Fitness",
    date: "Sat, Jun 6",
    time: "10:00 AM",
    startsAt: "2026-06-06T10:00:00+10:00",
    location: "Clovelly Beach",
    suburb: "Clovelly",
    distanceKm: 7.4,
    lat: -33.9141,
    lng: 151.2678,
    price: "$10",
    attendees: 21,
    capacity: 26,
    image: "/media/yoga.jpg",
    imageAlt: "Outdoor group preparing for an active meetup",
    description:
      "A calm snorkel and coastal walk for confident swimmers, ending with hot chips on the grass.",
    tags: ["snorkel", "manly", "outdoors", "fitness", "weekend"],
    lifeSignals: ["Active", "Weekend", "Outdoors"],
    fomo: "Best for people who want a whole Saturday plan with a small crew.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Turn an outdoor plan into a repeat weekend crew.",
  },
  {
    id: "parramatta-newcomers-dinner",
    title: "Leichhardt Newcomers Dinner",
    group: "Inner West Welcome Table",
    host: "Asha Kumar",
    category: "Food",
    date: "Sun, Jun 7",
    time: "6:30 PM",
    startsAt: "2026-06-07T18:30:00+10:00",
    location: "Bar Italia",
    suburb: "Leichhardt",
    distanceKm: 5.1,
    lat: -33.8835,
    lng: 151.1573,
    price: "$34",
    attendees: 10,
    capacity: 14,
    image: "/media/networking.jpg",
    imageAlt: "People meeting over dinner at a warm group table",
    description:
      "A small-table dinner for people in Western Sydney who want local friends without travelling into the CBD every time.",
    tags: ["parramatta", "dinner", "food", "new to town", "friends"],
    lifeSignals: ["New to Town", "Food", "Weekend"],
    fomo: "Strong fit for west-side locals building a nearby circle.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Help Western Sydney locals meet closer to home.",
  },
  {
    id: "redfern-photo-walk",
    title: "Redfern Photo Walk and Coffee",
    group: "Street Frames Sydney",
    host: "Leo Martin",
    category: "Creative",
    date: "Tue, Jun 9",
    time: "5:45 PM",
    startsAt: "2026-06-09T17:45:00+10:00",
    location: "Redfern Station",
    suburb: "Redfern",
    distanceKm: 2.7,
    lat: -33.8917,
    lng: 151.1989,
    price: "Free",
    attendees: 23,
    capacity: 32,
    image: "/media/concert.jpg",
    imageAlt: "Creative community group at an evening event",
    description:
      "A guided street-photo loop with simple prompts, paired walking, and coffee after for anyone using a phone or camera.",
    tags: ["photography", "redfern", "creative", "walk", "coffee"],
    lifeSignals: ["Creative", "Weeknights", "Curious"],
    fomo: "Great first event for people who like walking with a shared focus.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Use photography prompts to make conversation natural.",
  },
  {
    id: "coogee-ocean-swim",
    title: "Coogee Ocean Swim Buddies",
    group: "Eastern Beaches Run Club",
    host: "Nina Alvarez",
    category: "Fitness",
    date: "Wed, Jun 10",
    time: "7:00 AM",
    startsAt: "2026-06-10T07:00:00+10:00",
    location: "Coogee Surf Life Saving Club",
    suburb: "Coogee",
    distanceKm: 7.5,
    lat: -33.9225,
    lng: 151.2579,
    price: "Free",
    attendees: 16,
    capacity: 24,
    image: "/media/yoga.jpg",
    imageAlt: "Outdoor fitness group by the water",
    description:
      "A beginner-aware ocean swim meetup with pairs, safety check-ins, and coffee for anyone wanting a regular swim buddy.",
    tags: ["swimming", "coogee", "fitness", "morning", "coffee"],
    lifeSignals: ["Morning", "Active", "Wellness"],
    fomo: "Good fit for confident swimmers who still prefer not to go alone.",
    status: "Locked",
    booking: "Click-managed",
    relationshipGoal: "Make regular ocean swimming feel social and safer.",
  },
  {
    id: "sunrise-run-club-bay-run-loop",
    title: "Sunrise Run Club: Bay Run Loop",
    group: "Inner West Pacers",
    host: "Dylan Reyes",
    category: "Fitness",
    date: "Fri, May 29",
    time: "6:30 AM",
    startsAt: "2026-05-28T20:30:00.000Z",
    location: "Bay Run Boatshed",
    suburb: "Annandale",
    distanceKm: 3.9,
    lat: -33.8825,
    lng: 151.17,
    price: "Free",
    attendees: 31,
    capacity: 40,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Inner West Pacers hosts sunrise run club: bay run loop in Annandale. Find a steady running partner who shows up.",
    tags: ["running", "fitness", "morning", "outdoors", "accountability"],
    lifeSignals: ["Active", "Morning", "Consistent"],
    fomo: "Most runners come back three weeks straight.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find a steady running partner who shows up.",
  },
  {
    id: "vinyasa-flow-in-the-park",
    title: "Vinyasa Flow in the Park",
    group: "Slow Sundays Yoga",
    host: "Priya Shah",
    category: "Fitness",
    date: "Sat, May 30",
    time: "9:00 AM",
    startsAt: "2026-05-29T23:00:00.000Z",
    location: "Bicentennial Park",
    suburb: "Glebe",
    distanceKm: 2.5,
    lat: -33.877,
    lng: 151.1845,
    price: "$15",
    attendees: 18,
    capacity: 30,
    image: "/media/yoga.jpg",
    imageAlt: "People training together in a group fitness session",
    description:
      "Slow Sundays Yoga hosts vinyasa flow in the park in Glebe. Start the week grounded with new faces.",
    tags: ["yoga", "wellness", "outdoors", "morning", "low pressure"],
    lifeSignals: ["Wellness", "Calm", "Weekends"],
    fomo: "A calm crowd that lingers for tea after.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Start the week grounded with new faces.",
  },
  {
    id: "board-games-buds-night",
    title: "Board Games & Buds Night",
    group: "Tabletop Tuesdays",
    host: "Marcus Lim",
    category: "Social",
    date: "Sun, May 31",
    time: "6:30 PM",
    startsAt: "2026-05-31T08:30:00.000Z",
    location: "The Gamesmiths",
    suburb: "Newtown",
    distanceKm: 4.4,
    lat: -33.899,
    lng: 151.1785,
    price: "$8",
    attendees: 19,
    capacity: 24,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Tabletop Tuesdays hosts board games & buds night in Newtown. Turn one games night into a regular crew.",
    tags: ["games", "friends", "low pressure", "weeknights", "new to town"],
    lifeSignals: ["Ambivert", "Playful", "Weeknights"],
    fomo: "Beginners welcome — rules taught at every table.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Turn one games night into a regular crew.",
  },
  {
    id: "wine-watercolour-social",
    title: "Wine & Watercolour Social",
    group: "Brushes After Dark",
    host: "Eliza Fontaine",
    category: "Creative",
    date: "Mon, Jun 1",
    time: "7:00 PM",
    startsAt: "2026-06-01T09:00:00.000Z",
    location: "Bondi Pavilion Studio",
    suburb: "Bondi Beach",
    distanceKm: 6.5,
    lat: -33.8908,
    lng: 151.2748,
    price: "$42",
    attendees: 17,
    capacity: 20,
    image: "/media/concert.jpg",
    imageAlt: "A crowd enjoying live music together",
    description:
      "Brushes After Dark hosts wine & watercolour social in Bondi Beach. Make something with your hands and meet makers.",
    tags: ["creative", "art", "wine", "weeknights"],
    lifeSignals: ["Curious", "Creative", "Weeknights"],
    fomo: "Sells out most fortnights — grab a seat early.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Make something with your hands and meet makers.",
  },
  {
    id: "founders-coffee-early-stage",
    title: "Founders Coffee: Early Stage",
    group: "Sydney Builders",
    host: "Noah Whitfield",
    category: "Career",
    date: "Tue, Jun 2",
    time: "8:00 AM",
    startsAt: "2026-06-01T22:00:00.000Z",
    location: "Brickfields Bakery",
    suburb: "Chippendale",
    distanceKm: 2.2,
    lat: -33.887,
    lng: 151.201,
    price: "Free",
    attendees: 22,
    capacity: 30,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Sydney Builders hosts founders coffee: early stage in Chippendale. Find a co-founder or a sounding board.",
    tags: ["founders", "career change", "networking", "morning"],
    lifeSignals: ["Driven", "Builder", "Morning"],
    fomo: "Half the room is pre-seed and shipping.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find a co-founder or a sounding board.",
  },
  {
    id: "dumpling-crawl-chinatown",
    title: "Dumpling Crawl: Marrickville",
    group: "Sydney Table Friends",
    host: "Lena Ortiz",
    category: "Food",
    date: "Wed, Jun 3",
    time: "6:30 PM",
    startsAt: "2026-06-03T08:30:00.000Z",
    location: "Marrickville Road Eats",
    suburb: "Marrickville",
    distanceKm: 6.8,
    lat: -33.9115,
    lng: 151.156,
    price: "$35",
    attendees: 11,
    capacity: 12,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Sydney Table Friends hosts dumpling crawl: chinatown in Marrickville. Make dinner the easiest first plan with strangers.",
    tags: ["food", "dumplings", "dinner", "new friends"],
    lifeSignals: ["Food", "Curious", "Weeknights"],
    fomo: "One seat left at a famously chatty table.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Make dinner the easiest first plan with strangers.",
  },
  {
    id: "sunset-sketch-jam",
    title: "Sunset Sketch Jam",
    group: "Rooftop Makers",
    host: "Eliza Fontaine",
    category: "Creative",
    date: "Thu, Jun 4",
    time: "5:30 PM",
    startsAt: "2026-06-04T07:30:00.000Z",
    location: "Marks Park",
    suburb: "Tamarama",
    distanceKm: 6.6,
    lat: -33.8987,
    lng: 151.2705,
    price: "$18",
    attendees: 20,
    capacity: 25,
    image: "/media/concert.jpg",
    imageAlt: "A crowd enjoying live music together",
    description:
      "Rooftop Makers hosts sunset sketch jam in Tamarama. Draw beside people who love making things.",
    tags: ["creative", "art", "photography", "weekend"],
    lifeSignals: ["Creative", "Curious", "Weekends"],
    fomo: "Golden hour over the harbour, every time.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Draw beside people who love making things.",
  },
  {
    id: "beginner-bouldering-meet",
    title: "Beginner Bouldering Meet",
    group: "Send It Social",
    host: "Theo Morgan",
    category: "Fitness",
    date: "Fri, Jun 5",
    time: "6:00 PM",
    startsAt: "2026-06-05T08:00:00.000Z",
    location: "BlocHaus Alexandria",
    suburb: "Alexandria",
    distanceKm: 4.8,
    lat: -33.911,
    lng: 151.198,
    price: "$25",
    attendees: 14,
    capacity: 20,
    image: "/media/yoga.jpg",
    imageAlt: "People training together in a group fitness session",
    description:
      "Send It Social hosts beginner bouldering meet in Alexandria. Find a climbing partner without the gym cliques.",
    tags: ["fitness", "climbing", "accountability", "weeknights"],
    lifeSignals: ["Active", "Playful", "Weeknights"],
    fomo: "Coaches pair first-timers with regulars.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find a climbing partner without the gym cliques.",
  },
  {
    id: "slow-dating-walk-talk",
    title: "Slow Dating: Walk & Talk",
    group: "Real Conversations Sydney",
    host: "Amelia Hart",
    category: "Relationships",
    date: "Sat, Jun 6",
    time: "4:00 PM",
    startsAt: "2026-06-06T06:00:00.000Z",
    location: "Bondi to Bronte Coastal Walk",
    suburb: "Bondi Beach",
    distanceKm: 6.7,
    lat: -33.8948,
    lng: 151.2743,
    price: "$29",
    attendees: 21,
    capacity: 24,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Real Conversations Sydney hosts slow dating: walk & talk in Bondi Beach. Meet through a shared walk before matching.",
    tags: ["dating", "relationships", "outdoors", "weekend"],
    lifeSignals: ["Ready", "Curious", "Weekends"],
    fomo: "Mostly relationship-minded singles, small group.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Meet through a shared walk before matching.",
  },
  {
    id: "jazz-negronis",
    title: "Jazz & Negronis",
    group: "After Hours Listening Club",
    host: "Sofia Marchetti",
    category: "Music",
    date: "Sun, Jun 7",
    time: "8:00 PM",
    startsAt: "2026-06-07T10:00:00.000Z",
    location: "The Eastern",
    suburb: "Bondi Junction",
    distanceKm: 4.6,
    lat: -33.8918,
    lng: 151.2508,
    price: "$32",
    attendees: 33,
    capacity: 40,
    image: "/media/concert.jpg",
    imageAlt: "A crowd enjoying live music together",
    description:
      "After Hours Listening Club hosts jazz & negronis in Bondi Junction. Use music taste as a gentle matching signal.",
    tags: ["jazz", "live music", "weeknights"],
    lifeSignals: ["Curious", "Music", "Weeknights"],
    fomo: "Shared tables make it easy to talk between sets.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Use music taste as a gentle matching signal.",
  },
  {
    id: "new-in-town-mixer",
    title: "New In Town Mixer",
    group: "Sydney First-Timers Social Club",
    host: "Maya Chen",
    category: "Social",
    date: "Mon, Jun 8",
    time: "6:00 PM",
    startsAt: "2026-06-08T08:00:00.000Z",
    location: "The Bank Hotel",
    suburb: "Newtown",
    distanceKm: 4.4,
    lat: -33.8985,
    lng: 151.1782,
    price: "$10",
    attendees: 38,
    capacity: 50,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Sydney First-Timers Social Club hosts new in town mixer in Newtown. Leave with two people to text next week.",
    tags: ["friends", "new to town", "sydney", "low pressure"],
    lifeSignals: ["New to Town", "Ambivert", "Weeknights"],
    fomo: "Built for people who moved here in the last year.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Leave with two people to text next week.",
  },
  {
    id: "parkrun-pancakes",
    title: "Parkrun + Pancakes",
    group: "Weekend Wanderers",
    host: "Dylan Reyes",
    category: "Fitness",
    date: "Wed, Jun 10",
    time: "7:00 AM",
    startsAt: "2026-06-09T21:00:00.000Z",
    location: "Sydney Park parkrun",
    suburb: "St Peters",
    distanceKm: 5.1,
    lat: -33.91,
    lng: 151.185,
    price: "Free",
    attendees: 41,
    capacity: 60,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Weekend Wanderers hosts parkrun + pancakes in St Peters. Make Saturday mornings a social ritual.",
    tags: ["running", "fitness", "morning", "weekend", "outdoors"],
    lifeSignals: ["Active", "Morning", "Weekends"],
    fomo: "Free 5k then pancakes — no pace pressure.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Make Saturday mornings a social ritual.",
  },
  {
    id: "pottery-for-total-beginners",
    title: "Pottery for Total Beginners",
    group: "Mud & Mates",
    host: "Hana Watanabe",
    category: "Creative",
    date: "Thu, Jun 11",
    time: "11:00 AM",
    startsAt: "2026-06-11T01:00:00.000Z",
    location: "Clay Studio Marrickville",
    suburb: "Marrickville",
    distanceKm: 6.7,
    lat: -33.9105,
    lng: 151.1568,
    price: "$55",
    attendees: 12,
    capacity: 14,
    image: "/media/concert.jpg",
    imageAlt: "A crowd enjoying live music together",
    description:
      "Mud & Mates hosts pottery for total beginners in Marrickville. Get your hands messy beside friendly strangers.",
    tags: ["pottery", "creative", "weekend"],
    lifeSignals: ["Creative", "Calm", "Weekends"],
    fomo: "Two wheels left — everything else is booked.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Get your hands messy beside friendly strangers.",
  },
  {
    id: "long-lunch-shared-plates",
    title: "Long Lunch: Shared Plates",
    group: "Sydney Table Friends",
    host: "Lena Ortiz",
    category: "Food",
    date: "Fri, Jun 12",
    time: "12:30 PM",
    startsAt: "2026-06-12T02:30:00.000Z",
    location: "North Bondi RSL",
    suburb: "North Bondi",
    distanceKm: 7,
    lat: -33.889,
    lng: 151.281,
    price: "$48",
    attendees: 7,
    capacity: 10,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Sydney Table Friends hosts long lunch: shared plates in North Bondi. Turn a long lunch into a new friend group.",
    tags: ["food", "dinner", "restaurant", "new friends"],
    lifeSignals: ["Food", "Curious", "Weekends"],
    fomo: "Hosted seating so no one eats alone.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Turn a long lunch into a new friend group.",
  },
  {
    id: "women-in-tech-coffee-career",
    title: "Women in Tech: Coffee & Career",
    group: "Sydney Builders",
    host: "Noah Whitfield",
    category: "Career",
    date: "Sat, Jun 13",
    time: "8:30 AM",
    startsAt: "2026-06-12T22:30:00.000Z",
    location: "Spice Alley",
    suburb: "Chippendale",
    distanceKm: 2.1,
    lat: -33.8855,
    lng: 151.1985,
    price: "Free",
    attendees: 27,
    capacity: 35,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Sydney Builders hosts women in tech: coffee & career in Chippendale. Find a peer or mentor for your next move.",
    tags: ["women", "career change", "networking", "confidence", "morning"],
    lifeSignals: ["Driven", "Builder", "Morning"],
    fomo: "Mentors and switchers share the same table.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find a peer or mentor for your next move.",
  },
  {
    id: "harbour-sunset-picnic",
    title: "Coastal Sunset Picnic",
    group: "Sydney First-Timers Social Club",
    host: "Maya Chen",
    category: "Social",
    date: "Sun, Jun 14",
    time: "5:00 PM",
    startsAt: "2026-06-14T07:00:00.000Z",
    location: "Tamarama Beach Reserve",
    suburb: "Tamarama",
    distanceKm: 6.5,
    lat: -33.899,
    lng: 151.27,
    price: "Free",
    attendees: 29,
    capacity: 45,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Sydney First-Timers Social Club hosts harbour sunset picnic in Tamarama. Make familiar faces before the next weekend.",
    tags: ["friends", "outdoors", "weekend", "low pressure"],
    lifeSignals: ["Ambivert", "Calm", "Weekends"],
    fomo: "BYO blanket — host brings the icebreakers.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Make familiar faces before the next weekend.",
  },
  {
    id: "crossfit-skills-partner-drills",
    title: "CrossFit Skills: Partner Drills",
    group: "Inner West Fitness Mates",
    host: "Theo Morgan",
    category: "Fitness",
    date: "Tue, Jun 16",
    time: "7:30 AM",
    startsAt: "2026-06-15T21:30:00.000Z",
    location: "Norton Street Box",
    suburb: "Leichhardt",
    distanceKm: 5.1,
    lat: -33.884,
    lng: 151.1575,
    price: "$12",
    attendees: 20,
    capacity: 28,
    image: "/media/yoga.jpg",
    imageAlt: "People training together in a group fitness session",
    description:
      "Inner West Fitness Mates hosts crossfit skills: partner drills in Leichhardt. Find a training partner for a four-week streak.",
    tags: ["crossfit", "fitness", "training", "accountability"],
    lifeSignals: ["Active", "Morning", "Consistent"],
    fomo: "Scalable for every level, coffee after.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find a training partner for a four-week streak.",
  },
  {
    id: "open-mic-acoustic-night",
    title: "Open Mic & Acoustic Night",
    group: "After Hours Listening Club",
    host: "Sofia Marchetti",
    category: "Music",
    date: "Wed, Jun 17",
    time: "7:30 PM",
    startsAt: "2026-06-17T09:30:00.000Z",
    location: "The Duke of Enmore",
    suburb: "Enmore",
    distanceKm: 4.9,
    lat: -33.8987,
    lng: 151.17,
    price: "$15",
    attendees: 35,
    capacity: 50,
    image: "/media/concert.jpg",
    imageAlt: "A crowd enjoying live music together",
    description:
      "After Hours Listening Club hosts open mic & acoustic night in Enmore. Bond over shared taste between songs.",
    tags: ["live music", "indie", "weeknights"],
    lifeSignals: ["Music", "Playful", "Weeknights"],
    fomo: "Perform or just listen — both welcome.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Bond over shared taste between songs.",
  },
  {
    id: "speed-friending-inner-west",
    title: "Speed Friending: Inner West",
    group: "Tabletop Tuesdays",
    host: "Marcus Lim",
    category: "Social",
    date: "Thu, Jun 18",
    time: "6:00 PM",
    startsAt: "2026-06-18T08:00:00.000Z",
    location: "Carriageworks",
    suburb: "Eveleigh",
    distanceKm: 3.3,
    lat: -33.893,
    lng: 151.188,
    price: "$15",
    attendees: 30,
    capacity: 40,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Tabletop Tuesdays hosts speed friending: inner west in Eveleigh. Leave with a handful of new numbers.",
    tags: ["friends", "new to town", "low pressure", "weeknights"],
    lifeSignals: ["Ambivert", "New to Town", "Weeknights"],
    fomo: "Rotating chats so you meet everyone once.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Leave with a handful of new numbers.",
  },
  {
    id: "saturday-surf-school",
    title: "Saturday Surf School",
    group: "Send It Social",
    host: "Dylan Reyes",
    category: "Fitness",
    date: "Fri, Jun 19",
    time: "8:00 AM",
    startsAt: "2026-06-18T22:00:00.000Z",
    location: "Let's Go Surfing",
    suburb: "Bondi Beach",
    distanceKm: 6.9,
    lat: -33.89,
    lng: 151.28,
    price: "$45",
    attendees: 13,
    capacity: 16,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Send It Social hosts saturday surf school in Bondi Beach. Try something new beside an encouraging crew.",
    tags: ["fitness", "outdoors", "weekend", "beginners"],
    lifeSignals: ["Active", "Playful", "Weekends"],
    fomo: "Boards and wetsuits included for first-timers.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Try something new beside an encouraging crew.",
  },
  {
    id: "cheese-natural-wine-101",
    title: "Cheese & Natural Wine 101",
    group: "Brushes After Dark",
    host: "Eliza Fontaine",
    category: "Food",
    date: "Sun, Jun 21",
    time: "6:00 PM",
    startsAt: "2026-06-21T08:00:00.000Z",
    location: "Bondi Wine Merchants",
    suburb: "Bondi",
    distanceKm: 5.5,
    lat: -33.892,
    lng: 151.262,
    price: "$52",
    attendees: 15,
    capacity: 18,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Brushes After Dark hosts cheese & natural wine 101 in Bondi. Discover a new favourite next to new people.",
    tags: ["food", "wine", "weeknights", "new friends"],
    lifeSignals: ["Curious", "Food", "Weeknights"],
    fomo: "Guided tasting keeps conversation flowing.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Discover a new favourite next to new people.",
  },
  {
    id: "mindful-morning-breath-walk",
    title: "Mindful Morning: Breath & Walk",
    group: "Slow Sundays Yoga",
    host: "Priya Shah",
    category: "Fitness",
    date: "Mon, Jun 22",
    time: "7:00 AM",
    startsAt: "2026-06-21T21:00:00.000Z",
    location: "Coogee Beach",
    suburb: "Coogee",
    distanceKm: 7.4,
    lat: -33.9215,
    lng: 151.2585,
    price: "Free",
    attendees: 16,
    capacity: 30,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Slow Sundays Yoga hosts mindful morning: breath & walk in Coogee. Trade hellos with a calm weekend crowd.",
    tags: ["wellness", "outdoors", "morning", "low pressure"],
    lifeSignals: ["Calm", "Wellness", "Morning"],
    fomo: "A gentle start with a coffee debrief after.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Trade hellos with a calm weekend crowd.",
  },
  {
    id: "indie-film-club-screening-night",
    title: "Indie Film Club: Screening Night",
    group: "After Hours Listening Club",
    host: "Sofia Marchetti",
    category: "Creative",
    date: "Tue, Jun 23",
    time: "7:00 PM",
    startsAt: "2026-06-23T09:00:00.000Z",
    location: "Chippendale Hall",
    suburb: "Chippendale",
    distanceKm: 2.3,
    lat: -33.888,
    lng: 151.1995,
    price: "$24",
    attendees: 28,
    capacity: 35,
    image: "/media/concert.jpg",
    imageAlt: "A crowd enjoying live music together",
    description:
      "After Hours Listening Club hosts indie film club: screening night in Chippendale. Meet people through what you both love watching.",
    tags: ["creative", "film", "weeknights"],
    lifeSignals: ["Curious", "Creative", "Weeknights"],
    fomo: "Discussion over a drink after the credits.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Meet people through what you both love watching.",
  },
  {
    id: "volunteer-garden-working-bee",
    title: "Volunteer Garden Working Bee",
    group: "Neighbourhood Roots",
    host: "Hana Watanabe",
    category: "Community",
    date: "Wed, Jun 24",
    time: "9:00 AM",
    startsAt: "2026-06-23T23:00:00.000Z",
    location: "Erskineville Community Garden",
    suburb: "Erskineville",
    distanceKm: 4.3,
    lat: -33.902,
    lng: 151.185,
    price: "Free",
    attendees: 14,
    capacity: 25,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Neighbourhood Roots hosts volunteer garden working bee in Erskineville. Meet neighbours while doing something good.",
    tags: ["community", "volunteering", "outdoors", "weekend"],
    lifeSignals: ["Calm", "Giving", "Weekends"],
    fomo: "Hands-on, low pressure, plenty of chatting.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Meet neighbours while doing something good.",
  },
  {
    id: "dog-owners-social-walk",
    title: "Dog Owners' Social Walk",
    group: "Neighbourhood Roots",
    host: "Marcus Lim",
    category: "Community",
    date: "Thu, Jun 25",
    time: "4:30 PM",
    startsAt: "2026-06-25T06:30:00.000Z",
    location: "Jubilee Park",
    suburb: "Glebe",
    distanceKm: 2.5,
    lat: -33.8755,
    lng: 151.183,
    price: "Free",
    attendees: 22,
    capacity: 30,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Neighbourhood Roots hosts dog owners' social walk in Glebe. Find regulars for your weekend dog walks.",
    tags: ["pets", "community", "outdoors", "weekend", "low pressure"],
    lifeSignals: ["Playful", "Giving", "Weekends"],
    fomo: "Dogs break the ice so you don't have to.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find regulars for your weekend dog walks.",
  },
  {
    id: "founders-dinner-table-of-ten",
    title: "Founders Dinner: Table of Ten",
    group: "Sydney Builders",
    host: "Noah Whitfield",
    category: "Career",
    date: "Sat, Jun 27",
    time: "7:00 PM",
    startsAt: "2026-06-27T09:00:00.000Z",
    location: "Continental Deli",
    suburb: "Newtown",
    distanceKm: 4.2,
    lat: -33.8978,
    lng: 151.1795,
    price: "$65",
    attendees: 8,
    capacity: 10,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Sydney Builders hosts founders dinner: table of ten in Newtown. Swap honest stories over a long dinner.",
    tags: ["founders", "networking", "dinner", "career change"],
    lifeSignals: ["Driven", "Builder", "Weeknights"],
    fomo: "One seat left at a candid founders' table.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Swap honest stories over a long dinner.",
  },
  {
    id: "bouldering-tacos",
    title: "Bouldering + Tacos",
    group: "Send It Social",
    host: "Theo Morgan",
    category: "Fitness",
    date: "Sun, Jun 28",
    time: "6:30 PM",
    startsAt: "2026-06-28T08:30:00.000Z",
    location: "Sydney Indoor Climbing Gym",
    suburb: "Waterloo",
    distanceKm: 3.7,
    lat: -33.9015,
    lng: 151.2055,
    price: "$28",
    attendees: 15,
    capacity: 22,
    image: "/media/yoga.jpg",
    imageAlt: "People training together in a group fitness session",
    description:
      "Send It Social hosts bouldering + tacos in Waterloo. Find a regular climbing partner.",
    tags: ["climbing", "fitness", "accountability", "weeknights"],
    lifeSignals: ["Active", "Playful", "Weeknights"],
    fomo: "Climb at your level, tacos after for everyone.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find a regular climbing partner.",
  },
  {
    id: "latte-art-throwdown",
    title: "Latte Art Throwdown",
    group: "Sydney Table Friends",
    host: "Lena Ortiz",
    category: "Food",
    date: "Mon, Jun 29",
    time: "10:00 AM",
    startsAt: "2026-06-29T00:00:00.000Z",
    location: "Coffee Alchemy",
    suburb: "Marrickville",
    distanceKm: 6.1,
    lat: -33.9075,
    lng: 151.162,
    price: "$18",
    attendees: 18,
    capacity: 24,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Sydney Table Friends hosts latte art throwdown in Marrickville. Caffeinate and connect with locals.",
    tags: ["coffee", "food", "weekend", "new friends"],
    lifeSignals: ["Curious", "Food", "Weekends"],
    fomo: "Watch baristas battle, then try it yourself.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Caffeinate and connect with locals.",
  },
  {
    id: "sunset-rooftop-sketch-jam",
    title: "Sunset Rooftop Sketch Jam",
    group: "Rooftop Makers",
    host: "Eliza Fontaine",
    category: "Creative",
    date: "Tue, Jun 30",
    time: "5:00 PM",
    startsAt: "2026-06-30T07:00:00.000Z",
    location: "UTS Broadway Rooftop",
    suburb: "Ultimo",
    distanceKm: 1.9,
    lat: -33.8835,
    lng: 151.199,
    price: "$20",
    attendees: 19,
    capacity: 25,
    image: "/media/concert.jpg",
    imageAlt: "A crowd enjoying live music together",
    description:
      "Rooftop Makers hosts sunset rooftop sketch jam in Ultimo. Make art beside fellow makers at golden hour.",
    tags: ["creative", "art", "photography", "weekend"],
    lifeSignals: ["Creative", "Curious", "Weekends"],
    fomo: "City skyline backdrop, all skill levels.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Make art beside fellow makers at golden hour.",
  },
  {
    id: "singles-hike-spit-to-manly",
    title: "Singles Hike: Bondi to Coogee",
    group: "Real Conversations Sydney",
    host: "Amelia Hart",
    category: "Relationships",
    date: "Wed, Jul 1",
    time: "9:00 AM",
    startsAt: "2026-06-30T23:00:00.000Z",
    location: "Bondi to Coogee Coastal Walk",
    suburb: "Bondi Beach",
    distanceKm: 6.7,
    lat: -33.895,
    lng: 151.2745,
    price: "$25",
    attendees: 23,
    capacity: 26,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Real Conversations Sydney hosts singles hike: spit to manly in Bondi Beach. Meet someone over a shared 10k walk.",
    tags: ["dating", "relationships", "outdoors", "weekend"],
    lifeSignals: ["Ready", "Active", "Weekends"],
    fomo: "Pairs rotate so you talk to everyone.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Meet someone over a shared 10k walk.",
  },
  {
    id: "trivia-tap-takeover",
    title: "Trivia & Tap Takeover",
    group: "Tabletop Tuesdays",
    host: "Marcus Lim",
    category: "Social",
    date: "Thu, Jul 2",
    time: "7:00 PM",
    startsAt: "2026-07-02T09:00:00.000Z",
    location: "The Riverview Hotel",
    suburb: "Balmain",
    distanceKm: 3,
    lat: -33.8565,
    lng: 151.18,
    price: "$10",
    attendees: 36,
    capacity: 48,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Tabletop Tuesdays hosts trivia & tap takeover in Balmain. Join a team and leave with new mates.",
    tags: ["games", "friends", "weeknights", "low pressure"],
    lifeSignals: ["Ambivert", "Playful", "Weeknights"],
    fomo: "Solo players get placed on a friendly team.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Join a team and leave with new mates.",
  },
  {
    id: "morning-sea-swim-squad",
    title: "Morning Sea Swim Squad",
    group: "Slow Sundays Yoga",
    host: "Priya Shah",
    category: "Fitness",
    date: "Fri, Jul 3",
    time: "6:45 AM",
    startsAt: "2026-07-02T20:45:00.000Z",
    location: "Bondi Icebergs",
    suburb: "Bondi Beach",
    distanceKm: 6.7,
    lat: -33.8917,
    lng: 151.2768,
    price: "Free",
    attendees: 19,
    capacity: 30,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Slow Sundays Yoga hosts morning sea swim squad in Bondi Beach. Find a brave morning-swim crew.",
    tags: ["swimming", "fitness", "outdoors", "morning", "wellness"],
    lifeSignals: ["Active", "Wellness", "Morning"],
    fomo: "Coffee debrief after every swim.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find a brave morning-swim crew.",
  },
  {
    id: "career-pivot-roundtable",
    title: "Career Pivot Roundtable",
    group: "Sydney Builders",
    host: "Noah Whitfield",
    category: "Career",
    date: "Sun, Jul 5",
    time: "6:00 PM",
    startsAt: "2026-07-05T08:00:00.000Z",
    location: "Precinct 75",
    suburb: "St Peters",
    distanceKm: 5.1,
    lat: -33.9085,
    lng: 151.182,
    price: "Free",
    attendees: 21,
    capacity: 30,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Sydney Builders hosts career pivot roundtable in St Peters. Get unstuck with people mid-pivot too.",
    tags: ["career change", "confidence", "networking", "weeknights"],
    lifeSignals: ["Driven", "Curious", "Weeknights"],
    fomo: "Bring one question, leave with five answers.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Get unstuck with people mid-pivot too.",
  },
  {
    id: "ramen-records",
    title: "Ramen & Records",
    group: "After Hours Listening Club",
    host: "Sofia Marchetti",
    category: "Food",
    date: "Tue, Jul 7",
    time: "6:30 PM",
    startsAt: "2026-07-07T08:30:00.000Z",
    location: "Rising Sun Workshop",
    suburb: "Newtown",
    distanceKm: 4.4,
    lat: -33.8995,
    lng: 151.18,
    price: "$38",
    attendees: 12,
    capacity: 16,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "After Hours Listening Club hosts ramen & records in Newtown. Bond over noodles and a shared playlist.",
    tags: ["food", "dinner", "jazz", "new friends"],
    lifeSignals: ["Food", "Music", "Weeknights"],
    fomo: "Vinyl spinning while you slurp — easy chats.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Bond over noodles and a shared playlist.",
  },
  {
    id: "beginner-salsa-social",
    title: "Beginner Salsa Social",
    group: "Brushes After Dark",
    host: "Sofia Marchetti",
    category: "Creative",
    date: "Thu, Jul 9",
    time: "7:30 PM",
    startsAt: "2026-07-09T09:30:00.000Z",
    location: "The Vanguard",
    suburb: "Newtown",
    distanceKm: 4.4,
    lat: -33.8992,
    lng: 151.1786,
    price: "$22",
    attendees: 27,
    capacity: 36,
    image: "/media/concert.jpg",
    imageAlt: "A crowd enjoying live music together",
    description:
      "Brushes After Dark hosts beginner salsa social in Newtown. Learn steps beside other first-timers.",
    tags: ["dance", "creative", "weeknights", "beginners"],
    lifeSignals: ["Playful", "Curious", "Weeknights"],
    fomo: "No partner needed — everyone rotates.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Learn steps beside other first-timers.",
  },
  {
    id: "coastal-cleanup-crew",
    title: "Coastal Cleanup Crew",
    group: "Neighbourhood Roots",
    host: "Hana Watanabe",
    category: "Community",
    date: "Sat, Jul 11",
    time: "9:30 AM",
    startsAt: "2026-07-10T23:30:00.000Z",
    location: "Gordons Bay",
    suburb: "Coogee",
    distanceKm: 7.3,
    lat: -33.918,
    lng: 151.262,
    price: "Free",
    attendees: 25,
    capacity: 40,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Neighbourhood Roots hosts coastal cleanup crew in Coogee. Do good and meet locals who care.",
    tags: ["community", "volunteering", "outdoors", "weekend"],
    lifeSignals: ["Giving", "Active", "Weekends"],
    fomo: "An hour of cleanup, then a beach picnic.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Do good and meet locals who care.",
  },
  {
    id: "sunday-roast-for-strangers",
    title: "Sunday Roast for Strangers",
    group: "Sydney Table Friends",
    host: "Lena Ortiz",
    category: "Food",
    date: "Sun, Jul 12",
    time: "1:00 PM",
    startsAt: "2026-07-12T03:00:00.000Z",
    location: "The Bearded Tit",
    suburb: "Redfern",
    distanceKm: 2.8,
    lat: -33.893,
    lng: 151.201,
    price: "$42",
    attendees: 9,
    capacity: 12,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Sydney Table Friends hosts sunday roast for strangers in Redfern. Make Sunday lunch a social default.",
    tags: ["food", "dinner", "new friends", "weekend"],
    lifeSignals: ["Food", "Ambivert", "Weekends"],
    fomo: "One long table, hosted introductions.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Make Sunday lunch a social default.",
  },
  {
    id: "photo-walk-laneways-light",
    title: "Photo Walk: Laneways & Light",
    group: "Rooftop Makers",
    host: "Eliza Fontaine",
    category: "Creative",
    date: "Tue, Jul 14",
    time: "4:00 PM",
    startsAt: "2026-07-14T06:00:00.000Z",
    location: "Spice Alley",
    suburb: "Chippendale",
    distanceKm: 2.1,
    lat: -33.8858,
    lng: 151.1988,
    price: "Free",
    attendees: 13,
    capacity: 20,
    image: "/media/concert.jpg",
    imageAlt: "A crowd enjoying live music together",
    description:
      "Rooftop Makers hosts photo walk: laneways & light in Chippendale. Shoot beside people who love the same frames.",
    tags: ["photography", "creative", "weekend", "outdoors"],
    lifeSignals: ["Creative", "Curious", "Weekends"],
    fomo: "All cameras welcome, phones included.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Shoot beside people who love the same frames.",
  },
  {
    id: "run-brunch-centennial",
    title: "Run & Brunch: Centennial",
    group: "Inner West Pacers",
    host: "Dylan Reyes",
    category: "Fitness",
    date: "Thu, Jul 16",
    time: "8:00 AM",
    startsAt: "2026-07-15T22:00:00.000Z",
    location: "Queens Park",
    suburb: "Queens Park",
    distanceKm: 5.2,
    lat: -33.897,
    lng: 151.254,
    price: "Free",
    attendees: 34,
    capacity: 50,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "Inner West Pacers hosts run & brunch: centennial in Queens Park. Lock in a weekend running ritual.",
    tags: ["running", "fitness", "morning", "weekend"],
    lifeSignals: ["Active", "Morning", "Weekends"],
    fomo: "Easy 5k loop then a long brunch.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Lock in a weekend running ritual.",
  },
  {
    id: "singles-cooking-class",
    title: "Singles Cooking Class",
    group: "Real Conversations Sydney",
    host: "Amelia Hart",
    category: "Relationships",
    date: "Sun, Jul 19",
    time: "6:00 PM",
    startsAt: "2026-07-19T08:00:00.000Z",
    location: "Sydney Cooking School",
    suburb: "Camperdown",
    distanceKm: 3.7,
    lat: -33.889,
    lng: 151.177,
    price: "$59",
    attendees: 14,
    capacity: 16,
    image: "/media/networking.jpg",
    imageAlt: "People talking and sharing food at a hosted event",
    description:
      "Real Conversations Sydney hosts singles cooking class in Camperdown. Meet someone over a shared recipe.",
    tags: ["dating", "relationships", "food", "weeknights"],
    lifeSignals: ["Ready", "Food", "Weeknights"],
    fomo: "Cook in pairs, taste as a group.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Meet someone over a shared recipe.",
  },
];

export const peopleCards: PeopleRecommendation[] = [
  {
    id: "maya",
    name: "Maya",
    initials: "MC",
    neighborhood: "Barangaroo",
    intent: "New friends",
    persona: "Curious Explorer",
    bio: "Moved back to Sydney and wants a reliable weekend circle for picnics, walks, and easy conversation.",
    tags: ["friends", "sydney", "new to town", "weekend", "low pressure"],
    matchReason: "Good first match for relaxed social plans and recurring friendship groups.",
    nextEventId: "new-friends-barangaroo",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "theo",
    name: "Theo",
    initials: "TM",
    neighborhood: "Marrickville",
    intent: "Fitness partner",
    persona: "Mindful Achiever",
    bio: "Training for consistency, not ego. Likes scalable CrossFit sessions and coffee after class.",
    tags: ["crossfit", "fitness", "training", "coffee", "accountability"],
    matchReason: "Best match for getting better at CrossFit without joining a clique.",
    nextEventId: "crossfit-coffee",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "amelia",
    name: "Amelia",
    initials: "AH",
    neighborhood: "Surry Hills",
    intent: "Relationship-minded",
    persona: "Deep Connector",
    bio: "Prefers hosted dinners, small tables, and dating events that start with real conversation.",
    tags: ["dating", "relationships", "dinner", "surry hills", "low pressure"],
    matchReason: "Strong fit for relationship events with structure and no awkward pressure.",
    nextEventId: "slow-dating-six",
    accent: "bg-[#f65858]",
  },
  {
    id: "noah",
    name: "Noah",
    initials: "NS",
    neighborhood: "Newtown",
    intent: "Creative circle",
    persona: "Creative Free-Spirit",
    bio: "Wants ordinary makers around a table: sketchbooks, side projects, brunch, and accountability.",
    tags: ["creative", "brunch", "newtown", "friends", "community"],
    matchReason: "Useful match for hobbies, making things, and becoming familiar through repetition.",
    nextEventId: "ordinary-creatives",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "priya",
    name: "Priya",
    initials: "PN",
    neighborhood: "The Rocks",
    intent: "Career support",
    persona: "Mindful Achiever",
    bio: "Changing industries and looking for peers who want practical encouragement, not stiff networking.",
    tags: ["career", "confidence", "walk", "networking", "support"],
    matchReason: "Right fit for career-change support and walking conversations.",
    nextEventId: "career-walk",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "lena",
    name: "Lena",
    initials: "LO",
    neighborhood: "Potts Point",
    intent: "Dinner friends",
    persona: "Deep Connector",
    bio: "Likes small restaurant tables, friendly hosts, and plans where nobody has to coordinate a group chat.",
    tags: ["restaurant", "dinner", "food", "new friends", "low pressure"],
    matchReason: "Strong fit for hosted dinner tables and solo-friendly food events.",
    nextEventId: "restaurant-table-eight",
    accent: "bg-[#f65858]",
  },
  {
    id: "grace",
    name: "Grace",
    initials: "GL",
    neighborhood: "Haymarket",
    intent: "Food crew",
    persona: "Social Adventurer",
    bio: "Always knows a good noodle shop and wants more weeknight dinner plans close to the city.",
    tags: ["dumplings", "dinner", "food", "new to town", "friends"],
    matchReason: "Good match for shared-table dinners and easy after-work food plans.",
    nextEventId: "haymarket-dumpling-night",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "marcus",
    name: "Marcus",
    initials: "MB",
    neighborhood: "Enmore",
    intent: "Music mates",
    persona: "Creative Free-Spirit",
    bio: "Usually at small gigs, record shops, and late sets, but wants to stop arriving alone.",
    tags: ["jazz", "live music", "enmore", "creative", "night"],
    matchReason: "Best match for low-pressure music nights and creative social plans.",
    nextEventId: "enmore-live-jazz",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "elise",
    name: "Elise",
    initials: "EG",
    neighborhood: "Bronte",
    intent: "Calm mornings",
    persona: "Mindful Achiever",
    bio: "Prefers early starts, gentle movement, tea after class, and people who do not rush connection.",
    tags: ["yoga", "wellness", "bronte", "morning", "low pressure"],
    matchReason: "Right fit for wellness events with structure and soft conversation.",
    nextEventId: "bronte-sunrise-yoga",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "mina",
    name: "Mina",
    initials: "MP",
    neighborhood: "Sydney CBD",
    intent: "Founder peers",
    persona: "Mindful Achiever",
    bio: "Building a services business and looking for candid breakfast chats with other women doing the same.",
    tags: ["career", "founders", "breakfast", "women", "networking"],
    matchReason: "Useful fit for practical career circles and founder accountability.",
    nextEventId: "women-founder-breakfast",
    accent: "bg-[#f65858]",
  },
  {
    id: "samira",
    name: "Samira",
    initials: "SH",
    neighborhood: "Kings Cross",
    intent: "Community work",
    persona: "Deep Connector",
    bio: "Likes useful volunteering, meal prep nights, and meeting people while doing something tangible.",
    tags: ["volunteering", "community", "food", "kings cross", "friends"],
    matchReason: "Strong fit for community events where conversation happens through a shared task.",
    nextEventId: "kings-cross-community-kitchen",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "ruby",
    name: "Ruby",
    initials: "RW",
    neighborhood: "Alexandria",
    intent: "Creative friends",
    persona: "Creative Free-Spirit",
    bio: "Wants pottery, sketchbooks, snacks, and people who are happy making imperfect things together.",
    tags: ["pottery", "creative", "alexandria", "weekend", "craft"],
    matchReason: "Great match for activity-led events that make small talk optional.",
    nextEventId: "alexandria-pottery-night",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "oscar",
    name: "Oscar",
    initials: "OF",
    neighborhood: "Glebe",
    intent: "Pub trivia",
    persona: "Social Adventurer",
    bio: "Knows random facts, likes friendly competition, and wants a regular Sunday team.",
    tags: ["trivia", "pub", "friends", "glebe", "games"],
    matchReason: "Best fit for team-based social plans where the activity breaks the ice.",
    nextEventId: "glebe-trivia-teamup",
    accent: "bg-[#f65858]",
  },
  {
    id: "hannah",
    name: "Hannah",
    initials: "HR",
    neighborhood: "North Sydney",
    intent: "Quiet socials",
    persona: "Deep Connector",
    bio: "Reads on the train, likes parks, and prefers softer events where silence is not awkward.",
    tags: ["books", "picnic", "north sydney", "quiet", "friends"],
    matchReason: "Right fit for quiet, low-pressure social plans with a built-in topic.",
    nextEventId: "north-sydney-book-swap",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "ben",
    name: "Ben",
    initials: "BA",
    neighborhood: "Manly",
    intent: "Weekend crew",
    persona: "Social Adventurer",
    bio: "Usually near the water, keen for low-admin outdoor plans and ferry-friendly weekend mates.",
    tags: ["snorkel", "manly", "outdoors", "fitness", "weekend"],
    matchReason: "Good fit for active Saturday events with enough time to actually talk.",
    nextEventId: "manly-snorkel-walk",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "asha",
    name: "Asha",
    initials: "AK",
    neighborhood: "Parramatta",
    intent: "Local friends",
    persona: "Curious Explorer",
    bio: "Wants a west-side circle for dinners, walks, and plans that do not always mean crossing town.",
    tags: ["parramatta", "dinner", "food", "new to town", "friends"],
    matchReason: "Strong fit for Western Sydney dinner plans and newcomer-friendly tables.",
    nextEventId: "parramatta-newcomers-dinner",
    accent: "bg-[#f65858]",
  },
  {
    id: "leo",
    name: "Leo",
    initials: "LM",
    neighborhood: "Redfern",
    intent: "Photo walks",
    persona: "Creative Free-Spirit",
    bio: "Carries a camera most evenings and likes walking conversations with a creative prompt.",
    tags: ["photography", "redfern", "creative", "walk", "coffee"],
    matchReason: "Useful match for creative walks where the route gives everyone something to notice.",
    nextEventId: "redfern-photo-walk",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "nina",
    name: "Nina",
    initials: "NA",
    neighborhood: "Coogee",
    intent: "Swim buddy",
    persona: "Mindful Achiever",
    bio: "Likes ocean swimming, regular routines, and people who take safety seriously without making it intense.",
    tags: ["swimming", "coogee", "fitness", "morning", "coffee"],
    matchReason: "Best fit for morning fitness routines and repeat swim buddies.",
    nextEventId: "coogee-ocean-swim",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "talia",
    name: "Talia",
    initials: "TB",
    neighborhood: "Bondi",
    intent: "Running friends",
    persona: "Social Adventurer",
    bio: "Runs for the post-run chat as much as the kilometres and likes mixed-pace groups.",
    tags: ["running", "bondi", "fitness", "morning", "coffee"],
    matchReason: "Good first match for coastal movement and social recovery stops.",
    nextEventId: "bondi-coastal-run",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "kai",
    name: "Kai",
    initials: "KW",
    neighborhood: "Camperdown",
    intent: "Neighbourhood crew",
    persona: "Curious Explorer",
    bio: "New to the inner west, owns too many tote bags, and wants useful local rituals.",
    tags: ["community", "pets", "coffee", "volunteering", "friends"],
    matchReason: "Strong fit for light community events and repeat local faces.",
    nextEventId: "dog-park-cleanup",
    accent: "bg-[#5f6f52]",
  },
];

export const groups = [
  {
    name: "Sydney First-Timers Social Club",
    members: "8,420",
    category: "Social",
    focus: "Making friends after moving, breakups, new jobs, or fresh starts.",
    cadence: "3 weekly events",
  },
  {
    name: "Inner West Fitness Mates",
    members: "3,180",
    category: "Fitness",
    focus: "CrossFit, running, climbing, and accountability partners.",
    cadence: "2 morning crews",
  },
  {
    name: "Real Conversations Sydney",
    members: "5,930",
    category: "Relationships",
    focus: "Relationship-minded dinners, walks, workshops, and quiet socials.",
    cadence: "Hosted tables",
  },
  {
    name: "Ordinary People Making Things",
    members: "2,760",
    category: "Creative",
    focus: "Creative hobbies, brunches, accountability circles, and local showcases.",
    cadence: "Monthly brunch",
  },
];

export const roleCards = [
  {
    title: "Regular users",
    eyebrow: "Attendees",
    body: "Create a profile, choose intent modes, take the Life Quiz, RSVP, save events, and Click privately on people.",
  },
  {
    title: "Merchants",
    eyebrow: "Event hosts",
    body: "Create events, choose Click-managed or external booking, manage attendees, and watch conversion by tag.",
  },
];

export const onboardingSteps = [
  "Intent selection",
  "Basic information",
  "Interest tags",
  "Optional social enrichment",
  "Email and photo verification",
  "Dashboard activation",
];

export const interestTagCategories = [
  ["Music", "Live Jazz", "House", "Karaoke", "Acoustic"],
  ["Arts", "Pottery", "Painting", "Life Drawing", "Crafts"],
  ["Food", "Brunch", "Wine Tasting", "Vegan Eats", "Cooking Classes"],
  ["Wellness", "Yoga", "Meditation", "Breathwork", "Ice Baths"],
  ["Fitness", "Pilates", "Boxing", "Running", "Rock Climbing"],
  ["Outdoors", "Beach Days", "Hiking", "Camping", "Kayaking"],
  ["Games", "Trivia", "Board Games", "Escape Rooms"],
  ["Community", "Dog Parks", "Volunteering", "Cleanups"],
];

export const lifeQuizSections = [
  {
    title: "Life stage and identity",
    output: "Life tags like New to Town, Pet Owner, New Parent, Traveller.",
  },
  {
    title: "Personality style",
    output: "Social energy: introvert, ambivert, extrovert.",
  },
  {
    title: "Availability",
    output: "Weeknights, weekends, morning, flexible schedule.",
  },
  {
    title: "Event style",
    output: "Small table, active, creative, high-energy, quiet setting.",
  },
  {
    title: "Energy and mood",
    output: "Curious, cautious, ready, rebuilding confidence.",
  },
];

export const musicTags = [
  "Pop",
  "Rock",
  "Jazz",
  "Electronic",
  "House",
  "Hip Hop",
  "R&B",
  "Indie",
  "Folk",
  "Classical",
  "Reggae",
  "Soul",
  "Funk",
  "Latin",
];

export const personaCards = [
  {
    title: "The Curious Explorer",
    body: "Socially flexible, open to trying new things, and comfortable in mixed groups.",
  },
  {
    title: "The Deep Connector",
    body: "Reflective, small-group oriented, and drawn to slower conversation.",
  },
  {
    title: "The Social Adventurer",
    body: "Outgoing, spontaneous, and pulled toward high-energy plans.",
  },
  {
    title: "The Mindful Achiever",
    body: "Goal-oriented, structured, and motivated by growth-based events.",
  },
];

export const dashboardSections = [
  ["Upcoming", "Confirmed RSVPs with unlocked location and attendee context."],
  ["Saved and waitlist", "Bookmarks, waitlist offers, and time-sensitive confirmations."],
  ["Click with Someone", "Three rotating compatibility cards refreshed every four hours."],
  ["Click Radar", "Nearby trending events with overlapping tags and privacy-safe nudges."],
  ["Suggested for You", "Events ranked by tags, persona, availability, and RSVP behavior."],
];

export const merchantModules = [
  ["Overview", "Total events, attendees, revenue, and conversion by booking model."],
  ["Event management", "Create, edit, price, tag, and submit events for review."],
  ["Attendees", "RSVP, payment, waitlist, and export-ready attendee status."],
  ["Analytics", "Views to RSVPs, popular tags, and audience composition."],
  ["Settings", "Business profile, payout method, notification preferences."],
];

export const adminModules = [
  ["Merchant management", "Approve or reject hosts, review verification, track compliance."],
  ["Event moderation", "Check tag accuracy, duplicates, photos, spam, and publish readiness."],
  ["User oversight", "Review verification, flags, profile reports, and suspensions."],
  ["Tag management", "Create, merge, archive, and govern Interest Tags."],
  ["Financial review", "Audit Stripe transactions, refunds, and merchant payouts."],
  ["System logs", "Track admin actions, merchant edits, and security events."],
];

export const architectureLayers = [
  ["Hosted starts", "Every event needs a named host, a clear start time, and a simple reason for strangers to talk."],
  ["Familiar paths", "Recurring groups, shared rituals, and nearby suggestions make it easier to show up a second time."],
  ["Private sparks", "Clicks stay private until mutual, then point people toward a real event instead of an empty chat thread."],
];

export const notificationRows = [
  ["RSVP confirmation", "Successful payment or free RSVP", "Email and in-app"],
  ["Waitlist promotion", "Spot opens", "Email with 15-minute confirmation"],
  ["Mutual Click", "Two private clicks match", "In-app event suggestion"],
  ["Soft nudge", "Potential match attends a saved event", "In-app banner"],
  ["Post-event feedback", "12 hours after event end", "In-app feedback card"],
];

export const securityRows = [
  ["Anonymous Clicks", "Clicks stay private until mutual and unlock an event suggestion, not a chat thread."],
  ["Verification gates", "Email and photo verification required before RSVP or Click actions."],
  ["RLS and RBAC", "Users, merchants, and admins see only the scopes their role permits."],
  ["Audit trails", "Admin approvals, overrides, financial edits, and moderation actions are logged."],
];

export const roadmapItems = [
  "React Native app with push notifications",
  "Behavior-based matching model",
  "Group RSVP and shared planning",
  "Merchant QR check-in tools",
  "Corporate and community partner portals",
];
