export type EventStatus =
  | "Featured"
  | "Live"
  | "Waitlist"
  | "Locked"
  | "Pending"
  | "Cancelled";

export type EventItem = {
  id: string;
  title: string;
  group: string;
  host: string;
  category: string;
  date: string;
  time: string;
  startsAt: string;
  location: string;
  suburb: string;
  distanceKm: number;
  lat: number;
  lng: number;
  price: string;
  attendees: number;
  capacity: number;
  image: string;
  imageAlt: string;
  description: string;
  tags: string[];
  lifeSignals: string[];
  fomo: string;
  status: EventStatus;
  booking: "Click-managed" | "External";
  relationshipGoal: string;
};

export type PeopleRecommendation = {
  id: string;
  name: string;
  initials: string;
  avatar?: string;
  neighborhood: string;
  intent: string;
  persona: string;
  bio: string;
  tags: string[];
  matchReason: string;
  nextEventId: string;
  accent: string;
};

/**
 * Curated portrait photos from Unsplash. Cycled deterministically by person id
 * so the same person always shows the same face. All images are 200x200,
 * face-cropped, and served via Unsplash's image CDN.
 */
const unsplashPortraits = [
  "1494790108377-be9c29b29330",
  "1500648767791-00dcc994a43e",
  "1438761681033-6461ffad8d80",
  "1517841905240-472988babdf9",
  "1531123897727-8f129e1688ce",
  "1506794778202-cad84cf45f1d",
  "1502823403499-6ccfcf4fb453",
  "1487412720507-e7ab37603c6f",
  "1539571696357-5a69c17a67c6",
  "1552058544-f2b08422138a",
  "1519085360753-af0119f7cbe7",
  "1521119989659-a83eee488004",
  "1534528741775-53994a69daeb",
  "1492562080023-ab3db95bfbce",
  "1463453091185-61582044d556",
  "1564564321837-a57b7070ac4f",
  "1546961342-091cbcb40d8d",
  "1504593811423-6dd665756598",
  "1513956589380-bad6acb9b9d4",
  "1573496359142-b8d87734a5a2",
];

function hashId(id: string) {
  let hash = 0;
  for (let i = 0; i < id.length; i++) {
    hash = (hash * 31 + id.charCodeAt(i)) >>> 0;
  }
  return hash;
}

export function avatarFor(person: { id: string; avatar?: string }) {
  if (person.avatar) return person.avatar;
  const photo = unsplashPortraits[hashId(person.id) % unsplashPortraits.length];
  return `https://images.unsplash.com/photo-${photo}?w=200&h=200&fit=crop&crop=faces&auto=format&q=80`;
}

export const navItems = [
  { label: "Discover", href: "/discover" },
  { label: "Events", href: "/events" },
  { label: "Dashboard", href: "/dashboard" },
  { label: "Merchant", href: "/merchant" },
  { label: "Admin", href: "/admin" },
];

export const animatedPrompts = [
  "I want to meet new friends in Newtown",
  "Find people for weekend coffee in Surry Hills",
  "I just moved to Marrickville and want a social group",
  "Show me low-pressure dinners in Bondi",
  "I want a fitness friend around Redfern",
  "Help me meet creative people in Glebe",
  "Find a walking group near Barangaroo",
  "I want to make friends in Parramatta",
];

export const starterPrompts = animatedPrompts.slice(0, 4);

export const categories = [
  "All",
  "Social",
  "Fitness",
  "Relationships",
  "Food",
  "Creative",
  "Career",
  "Community",
];

export const clickEvents: EventItem[] = [
  {
    id: "new-friends-barangaroo",
    title: "New Friends Picnic at Barangaroo",
    group: "Sydney First-Timers Social Club",
    host: "Maya Chen",
    category: "Social",
    date: "Fri, May 8",
    time: "6:30 PM",
    startsAt: "2026-05-08T18:30:00+10:00",
    location: "Barangaroo Reserve, Sydney",
    suburb: "Barangaroo",
    distanceKm: 1.4,
    lat: -33.857,
    lng: 151.201,
    price: "Free",
    attendees: 47,
    capacity: 60,
    image: "/media/open-yoga.jpg",
    imageAlt: "People gathering outdoors in a relaxed group class",
    description:
      "A hosted picnic for people who want easy conversation, shared snacks, and familiar faces for the next event.",
    tags: ["friends", "sydney", "new to town", "weekend", "low pressure"],
    lifeSignals: ["New to Town", "Ambivert", "Weekends"],
    fomo: "4 people you might Click with are already going.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Make two familiar faces before the next weekend.",
  },
  {
    id: "crossfit-coffee",
    title: "CrossFit Skills and Coffee Crew",
    group: "Inner West Fitness Mates",
    host: "Theo Morgan",
    category: "Fitness",
    date: "Sat, May 9",
    time: "8:00 AM",
    startsAt: "2026-05-09T08:00:00+10:00",
    location: "Marrickville Training Yard",
    suburb: "Marrickville",
    distanceKm: 7.8,
    lat: -33.913,
    lng: 151.155,
    price: "$12",
    attendees: 24,
    capacity: 32,
    image: "/media/yoga.jpg",
    imageAlt: "People training together in a group fitness session",
    description:
      "Technique-focused partner drills, scalable workouts, and post-session coffee for people who want consistency without gym cliques.",
    tags: ["crossfit", "fitness", "training", "coffee", "accountability"],
    lifeSignals: ["Fitness-Focused", "Active", "Morning"],
    fomo: "Popular with people building a four-week fitness streak.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Find a fitness partner for a four-week streak.",
  },
  {
    id: "slow-dating-six",
    title: "Slow Dating: Dinner Tables of Six",
    group: "Real Conversations Sydney",
    host: "Amelia Hart",
    category: "Relationships",
    date: "Thu, May 14",
    time: "7:00 PM",
    startsAt: "2026-05-14T19:00:00+10:00",
    location: "Surry Hills",
    suburb: "Surry Hills",
    distanceKm: 2.5,
    lat: -33.884,
    lng: 151.212,
    price: "$29",
    attendees: 40,
    capacity: 42,
    image: "/media/networking.jpg",
    imageAlt: "People talking at a warm hosted dinner event",
    description:
      "Hosted dinner tables where singles meet through small-group conversation first, with private mutual interest after the event.",
    tags: ["dating", "relationships", "dinner", "surry hills", "low pressure"],
    lifeSignals: ["Curious", "Ready", "Weeknights"],
    fomo: "Mostly relationship-minded guests who prefer small tables.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Meet people through conversation before matching.",
  },
  {
    id: "restaurant-table-eight",
    title: "Restaurant Meetup: Table for Eight",
    group: "Sydney Table Friends",
    host: "Lena Ortiz",
    category: "Food",
    date: "Fri, May 15",
    time: "7:00 PM",
    startsAt: "2026-05-15T19:00:00+10:00",
    location: "Bar Lucia, Potts Point",
    suburb: "Potts Point",
    distanceKm: 2.8,
    lat: -33.872,
    lng: 151.225,
    price: "$38",
    attendees: 6,
    capacity: 8,
    image: "/media/networking.jpg",
    imageAlt: "People sharing food and conversation at a restaurant table",
    description:
      "A hosted restaurant table for people who want dinner plans without the awkward group-chat setup. Arrive solo, sit with eight, and let the host open the first conversation.",
    tags: ["restaurant", "dinner", "food", "new friends", "low pressure"],
    lifeSignals: ["New to Town", "Food", "Weeknights"],
    fomo: "Only two seats left at a small table designed for easy conversation.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Make dinner feel like the easiest first plan with new people.",
  },
  {
    id: "ordinary-creatives",
    title: "Creative Brunch for Ordinary People",
    group: "Ordinary People Making Things",
    host: "Noah Singh",
    category: "Creative",
    date: "Sun, May 17",
    time: "10:30 AM",
    startsAt: "2026-05-17T10:30:00+10:00",
    location: "Newtown Community Hall",
    suburb: "Newtown",
    distanceKm: 4.7,
    lat: -33.897,
    lng: 151.179,
    price: "$18",
    attendees: 53,
    capacity: 70,
    image: "/media/concert.jpg",
    imageAlt: "Crowd at a warm local music and creative event",
    description:
      "A no-status brunch for writers, designers, builders, makers, and anyone who wants a recurring community around doing real things.",
    tags: ["creative", "brunch", "newtown", "friends", "community"],
    lifeSignals: ["Creative", "Weekend", "Curious Explorer"],
    fomo: "Strong overlap with makers, writers, and new locals.",
    status: "Featured",
    booking: "External",
    relationshipGoal: "Turn a hobby into a recurring group.",
  },
  {
    id: "career-walk",
    title: "Career Change Walk and Talk",
    group: "Sydney Career Switchers",
    host: "Priya Nair",
    category: "Career",
    date: "Wed, May 20",
    time: "6:00 PM",
    startsAt: "2026-05-20T18:00:00+10:00",
    location: "Circular Quay to The Rocks",
    suburb: "The Rocks",
    distanceKm: 0.9,
    lat: -33.859,
    lng: 151.209,
    price: "Free",
    attendees: 31,
    capacity: 45,
    image: "/media/networking.jpg",
    imageAlt: "People talking at a community meetup",
    description:
      "A walking meetup for people changing careers, building confidence, and looking for peers rather than formal networking.",
    tags: ["career", "confidence", "walk", "networking", "support"],
    lifeSignals: ["Busy Professional", "Balanced", "Weeknights"],
    fomo: "Good fit for people rebuilding confidence around work.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Meet peers who understand the same career transition.",
  },
  {
    id: "dog-park-cleanup",
    title: "Dog Park Coffee and Cleanup",
    group: "Inner City Community Mates",
    host: "Jules Park",
    category: "Community",
    date: "Sat, May 23",
    time: "9:00 AM",
    startsAt: "2026-05-23T09:00:00+10:00",
    location: "Camperdown Memorial Rest Park",
    suburb: "Camperdown",
    distanceKm: 4.2,
    lat: -33.888,
    lng: 151.176,
    price: "Free",
    attendees: 18,
    capacity: 36,
    image: "/media/open-yoga.jpg",
    imageAlt: "Outdoor community group meeting in a park",
    description:
      "A light volunteer morning for pet owners, locals, and people who want a natural reason to talk while doing something useful.",
    tags: ["community", "pets", "coffee", "volunteering", "friends"],
    lifeSignals: ["Pet Owner", "Community", "Weekend"],
    fomo: "Popular with pet owners and people new to Camperdown.",
    status: "Locked",
    booking: "Click-managed",
    relationshipGoal: "Meet locals through a useful shared ritual.",
  },
  {
    id: "bondi-coastal-run",
    title: "Bondi Coastal Run and Smoothies",
    group: "Eastern Beaches Run Club",
    host: "Talia Brooks",
    category: "Fitness",
    date: "Sun, May 24",
    time: "7:30 AM",
    startsAt: "2026-05-24T07:30:00+10:00",
    location: "Bondi Icebergs, Bondi Beach",
    suburb: "Bondi",
    distanceKm: 6.8,
    lat: -33.891,
    lng: 151.277,
    price: "Free",
    attendees: 34,
    capacity: 50,
    image: "/media/yoga.jpg",
    imageAlt: "People stretching before an outdoor fitness meetup",
    description:
      "A conversational coastal run for mixed paces, followed by smoothies and an easy stretch on the grass.",
    tags: ["running", "bondi", "fitness", "morning", "coffee"],
    lifeSignals: ["Morning", "Active", "Weekend"],
    fomo: "Popular with people who want fitness without a competitive vibe.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Find a familiar face for weekend movement.",
  },
  {
    id: "haymarket-dumpling-night",
    title: "Dumpling Night for New Locals",
    group: "Sydney Table Friends",
    host: "Grace Liu",
    category: "Food",
    date: "Mon, May 25",
    time: "6:45 PM",
    startsAt: "2026-05-25T18:45:00+10:00",
    location: "Dixon Street Food Court, Haymarket",
    suburb: "Haymarket",
    distanceKm: 1.1,
    lat: -33.879,
    lng: 151.204,
    price: "$22",
    attendees: 14,
    capacity: 18,
    image: "/media/networking.jpg",
    imageAlt: "People sharing casual food at a group table",
    description:
      "A small shared-table dinner where the host handles ordering, introductions, and keeping the conversation moving.",
    tags: ["dumplings", "dinner", "food", "new to town", "low pressure"],
    lifeSignals: ["New to Town", "Food", "Weeknights"],
    fomo: "A strong fit for people who want dinner plans after work.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Turn a simple dinner into a first Sydney circle.",
  },
  {
    id: "enmore-live-jazz",
    title: "Live Jazz at Enmore Back Room",
    group: "Late Set Listeners",
    host: "Marcus Bell",
    category: "Creative",
    date: "Tue, May 26",
    time: "8:00 PM",
    startsAt: "2026-05-26T20:00:00+10:00",
    location: "Enmore Road, Enmore",
    suburb: "Enmore",
    distanceKm: 5.3,
    lat: -33.899,
    lng: 151.171,
    price: "$18",
    attendees: 28,
    capacity: 40,
    image: "/media/concert.jpg",
    imageAlt: "Crowd listening to a small live music performance",
    description:
      "A hosted live jazz night for people who like music but do not want to arrive alone or force small talk.",
    tags: ["jazz", "live music", "enmore", "creative", "night"],
    lifeSignals: ["Music", "Weeknights", "Curious"],
    fomo: "Great overlap with music lovers and quieter creative people.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Make live music feel like a shared plan, not a solo errand.",
  },
  {
    id: "bronte-sunrise-yoga",
    title: "Bronte Sunrise Yoga and Tea",
    group: "Soft Start Sydney",
    host: "Elise Grant",
    category: "Fitness",
    date: "Wed, May 27",
    time: "6:30 AM",
    startsAt: "2026-05-27T06:30:00+10:00",
    location: "Bronte Park, Bronte",
    suburb: "Bronte",
    distanceKm: 7.1,
    lat: -33.904,
    lng: 151.264,
    price: "$15",
    attendees: 22,
    capacity: 30,
    image: "/media/yoga.jpg",
    imageAlt: "Outdoor group yoga session on grass",
    description:
      "Gentle yoga, warm tea, and a short intro circle before work. Designed for people easing back into social mornings.",
    tags: ["yoga", "wellness", "bronte", "morning", "low pressure"],
    lifeSignals: ["Morning", "Wellness", "Cautious"],
    fomo: "Most people come solo and leave with one familiar name.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Create a calm first meeting before the day gets busy.",
  },
  {
    id: "women-founder-breakfast",
    title: "Women Founders Breakfast Circle",
    group: "Sydney Career Switchers",
    host: "Mina Patel",
    category: "Career",
    date: "Thu, May 28",
    time: "8:00 AM",
    startsAt: "2026-05-28T08:00:00+10:00",
    location: "The Grounds of the City, Sydney CBD",
    suburb: "Sydney CBD",
    distanceKm: 0.4,
    lat: -33.869,
    lng: 151.208,
    price: "$32",
    attendees: 19,
    capacity: 24,
    image: "/media/networking.jpg",
    imageAlt: "People networking over breakfast",
    description:
      "A practical founder breakfast for women building, freelancing, switching lanes, or wanting a sharper peer circle.",
    tags: ["career", "founders", "breakfast", "women", "networking"],
    lifeSignals: ["Busy Professional", "Morning", "Growth"],
    fomo: "Nearly full with people comparing real work problems, not pitches.",
    status: "Waitlist",
    booking: "Click-managed",
    relationshipGoal: "Make professional support feel candid and useful.",
  },
  {
    id: "kings-cross-community-kitchen",
    title: "Community Kitchen Prep Night",
    group: "Inner City Community Mates",
    host: "Samira Haddad",
    category: "Community",
    date: "Fri, May 29",
    time: "5:30 PM",
    startsAt: "2026-05-29T17:30:00+10:00",
    location: "Wayside Chapel, Kings Cross",
    suburb: "Kings Cross",
    distanceKm: 2.2,
    lat: -33.873,
    lng: 151.223,
    price: "Free",
    attendees: 26,
    capacity: 35,
    image: "/media/open-yoga.jpg",
    imageAlt: "Community volunteers gathering outdoors",
    description:
      "Prep meals with a small volunteer crew, then share tea afterward. A useful way to meet people without performative networking.",
    tags: ["volunteering", "community", "food", "kings cross", "friends"],
    lifeSignals: ["Community", "Weeknights", "Helpful"],
    fomo: "Good fit for people who prefer doing something useful while talking.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Meet good people through a practical shared task.",
  },
  {
    id: "alexandria-pottery-night",
    title: "After-Work Pottery Night",
    group: "Ordinary People Making Things",
    host: "Ruby Walsh",
    category: "Creative",
    date: "Sat, May 30",
    time: "4:00 PM",
    startsAt: "2026-05-30T16:00:00+10:00",
    location: "Kil.n.it Studio, Alexandria",
    suburb: "Alexandria",
    distanceKm: 5.6,
    lat: -33.909,
    lng: 151.195,
    price: "$45",
    attendees: 18,
    capacity: 22,
    image: "/media/concert.jpg",
    imageAlt: "Creative group event with warm lighting",
    description:
      "Beginner-friendly pottery with hosted table prompts, a snack break, and zero expectation that the bowl turns out straight.",
    tags: ["pottery", "creative", "alexandria", "weekend", "craft"],
    lifeSignals: ["Creative", "Weekend", "Curious"],
    fomo: "A favourite for people who want a task to make conversation easier.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Give people a shared object to laugh about and remember.",
  },
  {
    id: "glebe-trivia-teamup",
    title: "Glebe Trivia Team-Up",
    group: "Pub Quiz People",
    host: "Oscar Finch",
    category: "Social",
    date: "Sun, May 31",
    time: "6:00 PM",
    startsAt: "2026-05-31T18:00:00+10:00",
    location: "The Toxteth Hotel, Glebe",
    suburb: "Glebe",
    distanceKm: 3.0,
    lat: -33.879,
    lng: 151.186,
    price: "$8",
    attendees: 41,
    capacity: 48,
    image: "/media/networking.jpg",
    imageAlt: "People talking at a local social event",
    description:
      "Arrive solo and get placed on a friendly trivia team. The host rotates teams after round two so nobody is stuck.",
    tags: ["trivia", "pub", "friends", "glebe", "games"],
    lifeSignals: ["Social Adventurer", "Weekend", "Games"],
    fomo: "Works well for people who want instant team energy.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Make a group game do the first-conversation work.",
  },
  {
    id: "north-sydney-book-swap",
    title: "North Sydney Book Swap Picnic",
    group: "Quiet Pages Club",
    host: "Hannah Reid",
    category: "Social",
    date: "Tue, Jun 2",
    time: "6:00 PM",
    startsAt: "2026-06-02T18:00:00+10:00",
    location: "St Leonards Park, North Sydney",
    suburb: "North Sydney",
    distanceKm: 4.1,
    lat: -33.831,
    lng: 151.209,
    price: "Free",
    attendees: 17,
    capacity: 28,
    image: "/media/open-yoga.jpg",
    imageAlt: "Relaxed outdoor social group sitting in a park",
    description:
      "Bring one book, swap stories about it, and join a low-key picnic for people who prefer quieter social plans.",
    tags: ["books", "picnic", "north sydney", "quiet", "friends"],
    lifeSignals: ["Introvert", "Weeknights", "Low Pressure"],
    fomo: "Designed for people who like a softer room and a reason to talk.",
    status: "Live",
    booking: "Click-managed",
    relationshipGoal: "Let a favourite book introduce people for you.",
  },
  {
    id: "manly-snorkel-walk",
    title: "Manly Snorkel Walk and Chips",
    group: "Harbour Weekend Crew",
    host: "Ben Archer",
    category: "Fitness",
    date: "Sat, Jun 6",
    time: "10:00 AM",
    startsAt: "2026-06-06T10:00:00+10:00",
    location: "Shelly Beach, Manly",
    suburb: "Manly",
    distanceKm: 10.9,
    lat: -33.801,
    lng: 151.297,
    price: "$10",
    attendees: 21,
    capacity: 26,
    image: "/media/yoga.jpg",
    imageAlt: "Outdoor group preparing for an active meetup",
    description:
      "A calm snorkel and coastal walk for confident swimmers, ending with hot chips and a ferry-friendly finish.",
    tags: ["snorkel", "manly", "outdoors", "fitness", "weekend"],
    lifeSignals: ["Active", "Weekend", "Outdoors"],
    fomo: "Best for people who want a whole Saturday plan with a small crew.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Turn an outdoor plan into a repeat weekend crew.",
  },
  {
    id: "parramatta-newcomers-dinner",
    title: "Parramatta Newcomers Dinner",
    group: "West Sydney Welcome Table",
    host: "Asha Kumar",
    category: "Food",
    date: "Sun, Jun 7",
    time: "6:30 PM",
    startsAt: "2026-06-07T18:30:00+10:00",
    location: "Lilymu, Parramatta",
    suburb: "Parramatta",
    distanceKm: 19.8,
    lat: -33.815,
    lng: 151.003,
    price: "$34",
    attendees: 10,
    capacity: 14,
    image: "/media/networking.jpg",
    imageAlt: "People meeting over dinner at a warm group table",
    description:
      "A small-table dinner for people in Western Sydney who want local friends without travelling into the CBD every time.",
    tags: ["parramatta", "dinner", "food", "new to town", "friends"],
    lifeSignals: ["New to Town", "Food", "Weekend"],
    fomo: "Strong fit for west-side locals building a nearby circle.",
    status: "Featured",
    booking: "Click-managed",
    relationshipGoal: "Help Western Sydney locals meet closer to home.",
  },
  {
    id: "redfern-photo-walk",
    title: "Redfern Photo Walk and Coffee",
    group: "Street Frames Sydney",
    host: "Leo Martin",
    category: "Creative",
    date: "Tue, Jun 9",
    time: "5:45 PM",
    startsAt: "2026-06-09T17:45:00+10:00",
    location: "Redfern Station, Redfern",
    suburb: "Redfern",
    distanceKm: 3.1,
    lat: -33.892,
    lng: 151.199,
    price: "Free",
    attendees: 23,
    capacity: 32,
    image: "/media/concert.jpg",
    imageAlt: "Creative community group at an evening event",
    description:
      "A guided street-photo loop with simple prompts, paired walking, and coffee after for anyone using a phone or camera.",
    tags: ["photography", "redfern", "creative", "walk", "coffee"],
    lifeSignals: ["Creative", "Weeknights", "Curious"],
    fomo: "Great first event for people who like walking with a shared focus.",
    status: "Live",
    booking: "External",
    relationshipGoal: "Use photography prompts to make conversation natural.",
  },
  {
    id: "coogee-ocean-swim",
    title: "Coogee Ocean Swim Buddies",
    group: "Eastern Beaches Run Club",
    host: "Nina Alvarez",
    category: "Fitness",
    date: "Wed, Jun 10",
    time: "7:00 AM",
    startsAt: "2026-06-10T07:00:00+10:00",
    location: "Coogee Surf Life Saving Club",
    suburb: "Coogee",
    distanceKm: 8.2,
    lat: -33.922,
    lng: 151.255,
    price: "Free",
    attendees: 16,
    capacity: 24,
    image: "/media/yoga.jpg",
    imageAlt: "Outdoor fitness group by the water",
    description:
      "A beginner-aware ocean swim meetup with pairs, safety check-ins, and coffee for anyone wanting a regular swim buddy.",
    tags: ["swimming", "coogee", "fitness", "morning", "coffee"],
    lifeSignals: ["Morning", "Active", "Wellness"],
    fomo: "Good fit for confident swimmers who still prefer not to go alone.",
    status: "Locked",
    booking: "Click-managed",
    relationshipGoal: "Make regular ocean swimming feel social and safer.",
  },
];

export const peopleCards: PeopleRecommendation[] = [
  {
    id: "maya",
    name: "Maya",
    initials: "MC",
    neighborhood: "Barangaroo",
    intent: "New friends",
    persona: "Curious Explorer",
    bio: "Moved back to Sydney and wants a reliable weekend circle for picnics, walks, and easy conversation.",
    tags: ["friends", "sydney", "new to town", "weekend", "low pressure"],
    matchReason: "Good first match for relaxed social plans and recurring friendship groups.",
    nextEventId: "new-friends-barangaroo",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "theo",
    name: "Theo",
    initials: "TM",
    neighborhood: "Marrickville",
    intent: "Fitness partner",
    persona: "Mindful Achiever",
    bio: "Training for consistency, not ego. Likes scalable CrossFit sessions and coffee after class.",
    tags: ["crossfit", "fitness", "training", "coffee", "accountability"],
    matchReason: "Best match for getting better at CrossFit without joining a clique.",
    nextEventId: "crossfit-coffee",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "amelia",
    name: "Amelia",
    initials: "AH",
    neighborhood: "Surry Hills",
    intent: "Relationship-minded",
    persona: "Deep Connector",
    bio: "Prefers hosted dinners, small tables, and dating events that start with real conversation.",
    tags: ["dating", "relationships", "dinner", "surry hills", "low pressure"],
    matchReason: "Strong fit for relationship events with structure and no awkward pressure.",
    nextEventId: "slow-dating-six",
    accent: "bg-[#f65858]",
  },
  {
    id: "noah",
    name: "Noah",
    initials: "NS",
    neighborhood: "Newtown",
    intent: "Creative circle",
    persona: "Creative Free-Spirit",
    bio: "Wants ordinary makers around a table: sketchbooks, side projects, brunch, and accountability.",
    tags: ["creative", "brunch", "newtown", "friends", "community"],
    matchReason: "Useful match for hobbies, making things, and becoming familiar through repetition.",
    nextEventId: "ordinary-creatives",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "priya",
    name: "Priya",
    initials: "PN",
    neighborhood: "The Rocks",
    intent: "Career support",
    persona: "Mindful Achiever",
    bio: "Changing industries and looking for peers who want practical encouragement, not stiff networking.",
    tags: ["career", "confidence", "walk", "networking", "support"],
    matchReason: "Right fit for career-change support and walking conversations.",
    nextEventId: "career-walk",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "lena",
    name: "Lena",
    initials: "LO",
    neighborhood: "Potts Point",
    intent: "Dinner friends",
    persona: "Deep Connector",
    bio: "Likes small restaurant tables, friendly hosts, and plans where nobody has to coordinate a group chat.",
    tags: ["restaurant", "dinner", "food", "new friends", "low pressure"],
    matchReason: "Strong fit for hosted dinner tables and solo-friendly food events.",
    nextEventId: "restaurant-table-eight",
    accent: "bg-[#f65858]",
  },
  {
    id: "grace",
    name: "Grace",
    initials: "GL",
    neighborhood: "Haymarket",
    intent: "Food crew",
    persona: "Social Adventurer",
    bio: "Always knows a good noodle shop and wants more weeknight dinner plans close to the city.",
    tags: ["dumplings", "dinner", "food", "new to town", "friends"],
    matchReason: "Good match for shared-table dinners and easy after-work food plans.",
    nextEventId: "haymarket-dumpling-night",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "marcus",
    name: "Marcus",
    initials: "MB",
    neighborhood: "Enmore",
    intent: "Music mates",
    persona: "Creative Free-Spirit",
    bio: "Usually at small gigs, record shops, and late sets, but wants to stop arriving alone.",
    tags: ["jazz", "live music", "enmore", "creative", "night"],
    matchReason: "Best match for low-pressure music nights and creative social plans.",
    nextEventId: "enmore-live-jazz",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "elise",
    name: "Elise",
    initials: "EG",
    neighborhood: "Bronte",
    intent: "Calm mornings",
    persona: "Mindful Achiever",
    bio: "Prefers early starts, gentle movement, tea after class, and people who do not rush connection.",
    tags: ["yoga", "wellness", "bronte", "morning", "low pressure"],
    matchReason: "Right fit for wellness events with structure and soft conversation.",
    nextEventId: "bronte-sunrise-yoga",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "mina",
    name: "Mina",
    initials: "MP",
    neighborhood: "Sydney CBD",
    intent: "Founder peers",
    persona: "Mindful Achiever",
    bio: "Building a services business and looking for candid breakfast chats with other women doing the same.",
    tags: ["career", "founders", "breakfast", "women", "networking"],
    matchReason: "Useful fit for practical career circles and founder accountability.",
    nextEventId: "women-founder-breakfast",
    accent: "bg-[#f65858]",
  },
  {
    id: "samira",
    name: "Samira",
    initials: "SH",
    neighborhood: "Kings Cross",
    intent: "Community work",
    persona: "Deep Connector",
    bio: "Likes useful volunteering, meal prep nights, and meeting people while doing something tangible.",
    tags: ["volunteering", "community", "food", "kings cross", "friends"],
    matchReason: "Strong fit for community events where conversation happens through a shared task.",
    nextEventId: "kings-cross-community-kitchen",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "ruby",
    name: "Ruby",
    initials: "RW",
    neighborhood: "Alexandria",
    intent: "Creative friends",
    persona: "Creative Free-Spirit",
    bio: "Wants pottery, sketchbooks, snacks, and people who are happy making imperfect things together.",
    tags: ["pottery", "creative", "alexandria", "weekend", "craft"],
    matchReason: "Great match for activity-led events that make small talk optional.",
    nextEventId: "alexandria-pottery-night",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "oscar",
    name: "Oscar",
    initials: "OF",
    neighborhood: "Glebe",
    intent: "Pub trivia",
    persona: "Social Adventurer",
    bio: "Knows random facts, likes friendly competition, and wants a regular Sunday team.",
    tags: ["trivia", "pub", "friends", "glebe", "games"],
    matchReason: "Best fit for team-based social plans where the activity breaks the ice.",
    nextEventId: "glebe-trivia-teamup",
    accent: "bg-[#f65858]",
  },
  {
    id: "hannah",
    name: "Hannah",
    initials: "HR",
    neighborhood: "North Sydney",
    intent: "Quiet socials",
    persona: "Deep Connector",
    bio: "Reads on the train, likes parks, and prefers softer events where silence is not awkward.",
    tags: ["books", "picnic", "north sydney", "quiet", "friends"],
    matchReason: "Right fit for quiet, low-pressure social plans with a built-in topic.",
    nextEventId: "north-sydney-book-swap",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "ben",
    name: "Ben",
    initials: "BA",
    neighborhood: "Manly",
    intent: "Weekend crew",
    persona: "Social Adventurer",
    bio: "Usually near the water, keen for low-admin outdoor plans and ferry-friendly weekend mates.",
    tags: ["snorkel", "manly", "outdoors", "fitness", "weekend"],
    matchReason: "Good fit for active Saturday events with enough time to actually talk.",
    nextEventId: "manly-snorkel-walk",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "asha",
    name: "Asha",
    initials: "AK",
    neighborhood: "Parramatta",
    intent: "Local friends",
    persona: "Curious Explorer",
    bio: "Wants a west-side circle for dinners, walks, and plans that do not always mean crossing town.",
    tags: ["parramatta", "dinner", "food", "new to town", "friends"],
    matchReason: "Strong fit for Western Sydney dinner plans and newcomer-friendly tables.",
    nextEventId: "parramatta-newcomers-dinner",
    accent: "bg-[#f65858]",
  },
  {
    id: "leo",
    name: "Leo",
    initials: "LM",
    neighborhood: "Redfern",
    intent: "Photo walks",
    persona: "Creative Free-Spirit",
    bio: "Carries a camera most evenings and likes walking conversations with a creative prompt.",
    tags: ["photography", "redfern", "creative", "walk", "coffee"],
    matchReason: "Useful match for creative walks where the route gives everyone something to notice.",
    nextEventId: "redfern-photo-walk",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "nina",
    name: "Nina",
    initials: "NA",
    neighborhood: "Coogee",
    intent: "Swim buddy",
    persona: "Mindful Achiever",
    bio: "Likes ocean swimming, regular routines, and people who take safety seriously without making it intense.",
    tags: ["swimming", "coogee", "fitness", "morning", "coffee"],
    matchReason: "Best fit for morning fitness routines and repeat swim buddies.",
    nextEventId: "coogee-ocean-swim",
    accent: "bg-[#5f6f52]",
  },
  {
    id: "talia",
    name: "Talia",
    initials: "TB",
    neighborhood: "Bondi",
    intent: "Running friends",
    persona: "Social Adventurer",
    bio: "Runs for the post-run chat as much as the kilometres and likes mixed-pace groups.",
    tags: ["running", "bondi", "fitness", "morning", "coffee"],
    matchReason: "Good first match for coastal movement and social recovery stops.",
    nextEventId: "bondi-coastal-run",
    accent: "bg-[#7edbd3]",
  },
  {
    id: "kai",
    name: "Kai",
    initials: "KW",
    neighborhood: "Camperdown",
    intent: "Neighbourhood crew",
    persona: "Curious Explorer",
    bio: "New to the inner west, owns too many tote bags, and wants useful local rituals.",
    tags: ["community", "pets", "coffee", "volunteering", "friends"],
    matchReason: "Strong fit for light community events and repeat local faces.",
    nextEventId: "dog-park-cleanup",
    accent: "bg-[#5f6f52]",
  },
];

export const groups = [
  {
    name: "Sydney First-Timers Social Club",
    members: "8,420",
    category: "Social",
    focus: "Making friends after moving, breakups, new jobs, or fresh starts.",
    cadence: "3 weekly events",
  },
  {
    name: "Inner West Fitness Mates",
    members: "3,180",
    category: "Fitness",
    focus: "CrossFit, running, climbing, and accountability partners.",
    cadence: "2 morning crews",
  },
  {
    name: "Real Conversations Sydney",
    members: "5,930",
    category: "Relationships",
    focus: "Relationship-minded dinners, walks, workshops, and quiet socials.",
    cadence: "Hosted tables",
  },
  {
    name: "Ordinary People Making Things",
    members: "2,760",
    category: "Creative",
    focus: "Creative hobbies, brunches, accountability circles, and local showcases.",
    cadence: "Monthly brunch",
  },
];

export const roleCards = [
  {
    title: "Regular users",
    eyebrow: "Attendees",
    body: "Create a profile, choose intent modes, take the Life Quiz, RSVP, save events, and Click privately on people.",
  },
  {
    title: "Merchants",
    eyebrow: "Event hosts",
    body: "Create events, choose Click-managed or external booking, manage attendees, and watch conversion by tag.",
  },
];

export const onboardingSteps = [
  "Intent selection",
  "Basic information",
  "Interest tags",
  "Optional social enrichment",
  "Email and photo verification",
  "Dashboard activation",
];

export const interestTagCategories = [
  ["Music", "Live Jazz", "House", "Karaoke", "Acoustic"],
  ["Arts", "Pottery", "Painting", "Life Drawing", "Crafts"],
  ["Food", "Brunch", "Wine Tasting", "Vegan Eats", "Cooking Classes"],
  ["Wellness", "Yoga", "Meditation", "Breathwork", "Ice Baths"],
  ["Fitness", "Pilates", "Boxing", "Running", "Rock Climbing"],
  ["Outdoors", "Beach Days", "Hiking", "Camping", "Kayaking"],
  ["Games", "Trivia", "Board Games", "Escape Rooms"],
  ["Community", "Dog Parks", "Volunteering", "Cleanups"],
];

export const lifeQuizSections = [
  {
    title: "Life stage and identity",
    output: "Life tags like New to Town, Pet Owner, New Parent, Traveller.",
  },
  {
    title: "Personality style",
    output: "Social energy: introvert, ambivert, extrovert.",
  },
  {
    title: "Availability",
    output: "Weeknights, weekends, morning, flexible schedule.",
  },
  {
    title: "Event style",
    output: "Small table, active, creative, high-energy, quiet setting.",
  },
  {
    title: "Energy and mood",
    output: "Curious, cautious, ready, rebuilding confidence.",
  },
];

export const musicTags = [
  "Pop",
  "Rock",
  "Jazz",
  "Electronic",
  "House",
  "Hip Hop",
  "R&B",
  "Indie",
  "Folk",
  "Classical",
  "Reggae",
  "Soul",
  "Funk",
  "Latin",
];

export const personaCards = [
  {
    title: "The Curious Explorer",
    body: "Socially flexible, open to trying new things, and comfortable in mixed groups.",
  },
  {
    title: "The Deep Connector",
    body: "Reflective, small-group oriented, and drawn to slower conversation.",
  },
  {
    title: "The Social Adventurer",
    body: "Outgoing, spontaneous, and pulled toward high-energy plans.",
  },
  {
    title: "The Mindful Achiever",
    body: "Goal-oriented, structured, and motivated by growth-based events.",
  },
];

export const dashboardSections = [
  ["Upcoming", "Confirmed RSVPs with unlocked location and attendee context."],
  ["Saved and waitlist", "Bookmarks, waitlist offers, and time-sensitive confirmations."],
  ["Click with Someone", "Three rotating compatibility cards refreshed every four hours."],
  ["Click Radar", "Nearby trending events with overlapping tags and privacy-safe nudges."],
  ["Suggested for You", "Events ranked by tags, persona, availability, and RSVP behavior."],
];

export const merchantModules = [
  ["Overview", "Total events, attendees, revenue, and conversion by booking model."],
  ["Event management", "Create, edit, price, tag, and submit events for review."],
  ["Attendees", "RSVP, payment, waitlist, and export-ready attendee status."],
  ["Analytics", "Views to RSVPs, popular tags, and audience composition."],
  ["Settings", "Business profile, payout method, notification preferences."],
];

export const adminModules = [
  ["Merchant management", "Approve or reject hosts, review verification, track compliance."],
  ["Event moderation", "Check tag accuracy, duplicates, photos, spam, and publish readiness."],
  ["User oversight", "Review verification, flags, profile reports, and suspensions."],
  ["Tag management", "Create, merge, archive, and govern Interest Tags."],
  ["Financial review", "Audit Stripe transactions, refunds, and merchant payouts."],
  ["System logs", "Track admin actions, merchant edits, and security events."],
];

export const architectureLayers = [
  ["Hosted starts", "Every event needs a named host, a clear start time, and a simple reason for strangers to talk."],
  ["Familiar paths", "Recurring groups, shared rituals, and nearby suggestions make it easier to show up a second time."],
  ["Private sparks", "Clicks stay private until mutual, then point people toward a real event instead of an empty chat thread."],
];

export const notificationRows = [
  ["RSVP confirmation", "Successful payment or free RSVP", "Email and in-app"],
  ["Waitlist promotion", "Spot opens", "Email with 15-minute confirmation"],
  ["Mutual Click", "Two private clicks match", "In-app event suggestion"],
  ["Soft nudge", "Potential match attends a saved event", "In-app banner"],
  ["Post-event feedback", "12 hours after event end", "In-app feedback card"],
];

export const securityRows = [
  ["Anonymous Clicks", "Clicks stay private until mutual and unlock an event suggestion, not a chat thread."],
  ["Verification gates", "Email and photo verification required before RSVP or Click actions."],
  ["RLS and RBAC", "Users, merchants, and admins see only the scopes their role permits."],
  ["Audit trails", "Admin approvals, overrides, financial edits, and moderation actions are logged."],
];

export const roadmapItems = [
  "React Native app with push notifications",
  "Behavior-based matching model",
  "Group RSVP and shared planning",
  "Merchant QR check-in tools",
  "Corporate and community partner portals",
];
