begin;

insert into tag_categories (name, slug, description) values
  ('Social', 'social', 'Friendship, low-pressure gatherings, and local community'),
  ('Fitness', 'fitness', 'Training, movement, and accountability'),
  ('Relationships', 'relationships', 'Dating and relationship-minded social events'),
  ('Food', 'food', 'Restaurants, shared plates, dinners, and low-pressure table plans'),
  ('Creative', 'creative', 'Making, writing, art, music, and culture'),
  ('Career', 'career', 'Career change, networking, and professional support'),
  ('Community', 'community', 'Volunteering, neighbourhood rituals, and local action'),
  ('Music', 'music', 'Music taste used as a subtle matching signal'),
  ('Life', 'life', 'Life Quiz generated tags')
on conflict (slug) do nothing;

with category_lookup as (
  select id, slug from tag_categories
)
insert into tags (category_id, label, slug, tag_type, admin_managed)
select category_lookup.id, seed.label, seed.slug, seed.tag_type, seed.admin_managed
from (
  values
    ('social', 'Friends', 'friends', 'interest', true),
    ('social', 'New to Town', 'new-to-town', 'life', false),
    ('social', 'Low Pressure', 'low-pressure', 'vibe', true),
    ('social', 'Games', 'games', 'interest', true),
    ('social', 'Books', 'books', 'interest', true),
    ('social', 'Quiet', 'quiet', 'vibe', true),
    ('fitness', 'CrossFit', 'crossfit', 'interest', true),
    ('fitness', 'Fitness', 'fitness', 'interest', true),
    ('fitness', 'Accountability', 'accountability', 'vibe', true),
    ('fitness', 'Running', 'running', 'interest', true),
    ('fitness', 'Yoga', 'yoga', 'interest', true),
    ('fitness', 'Swimming', 'swimming', 'interest', true),
    ('fitness', 'Outdoors', 'outdoors', 'interest', true),
    ('fitness', 'Morning', 'morning', 'life', false),
    ('fitness', 'Wellness', 'wellness', 'interest', true),
    ('relationships', 'Dating', 'dating', 'interest', true),
    ('relationships', 'Relationships', 'relationships', 'interest', true),
    ('food', 'Restaurant', 'restaurant', 'interest', true),
    ('food', 'Dinner', 'dinner', 'interest', true),
    ('food', 'Food', 'food', 'interest', true),
    ('food', 'Dumplings', 'dumplings', 'interest', true),
    ('creative', 'Creative', 'creative', 'interest', true),
    ('creative', 'Brunch', 'brunch', 'interest', true),
    ('creative', 'Live Music', 'live-music', 'interest', true),
    ('creative', 'Pottery', 'pottery', 'interest', true),
    ('creative', 'Photography', 'photography', 'interest', true),
    ('career', 'Career Change', 'career-change', 'interest', true),
    ('career', 'Confidence', 'confidence', 'life', false),
    ('career', 'Founders', 'founders', 'interest', true),
    ('career', 'Women', 'women', 'interest', true),
    ('community', 'Pets', 'pets', 'interest', true),
    ('community', 'Community', 'community', 'interest', true),
    ('community', 'Volunteering', 'volunteering', 'interest', true),
    ('music', 'Jazz', 'jazz', 'music', true),
    ('music', 'Indie', 'indie', 'music', true),
    ('life', 'Ambivert', 'ambivert', 'life', false),
    ('life', 'Weekend', 'weekend', 'life', false)
) as seed(category_slug, label, slug, tag_type, admin_managed)
join category_lookup on category_lookup.slug = seed.category_slug
on conflict (slug) do nothing;

insert into profiles (
  auth_subject,
  role,
  email,
  display_name,
  age,
  gender,
  suburb,
  city,
  bio,
  photo_url,
  connection_intents,
  email_verified_at,
  photo_verified_at
) values
  (
    'seed:maya',
    'attendee',
    'maya@click.local',
    'Maya Chen',
    31,
    'woman',
    'Barangaroo',
    'Sydney',
    'Moved back to Sydney and wants a reliable weekend circle for picnics, walks, and easy conversation.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:theo',
    'merchant',
    'theo@click.local',
    'Theo Morgan',
    34,
    'man',
    'Marrickville',
    'Sydney',
    'Training for consistency, not ego. Runs scalable CrossFit sessions and coffee after class.',
    null,
    '{friendship,networking}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:amelia',
    'merchant',
    'amelia@click.local',
    'Amelia Hart',
    36,
    'woman',
    'Surry Hills',
    'Sydney',
    'Hosts relationship-minded dinners that start with real conversation.',
    null,
    '{dating}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:noah',
    'merchant',
    'noah@click.local',
    'Noah Singh',
    29,
    'man',
    'Newtown',
    'Sydney',
    'Wants ordinary makers around a table: sketchbooks, side projects, brunch, and accountability.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:priya',
    'merchant',
    'priya@click.local',
    'Priya Nair',
    38,
    'woman',
    'The Rocks',
    'Sydney',
    'Changing industries and looking for practical encouragement, not stiff networking.',
    null,
    '{networking,friendship}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:admin',
    'admin',
    'admin@click.local',
    'Click Admin',
    null,
    null,
    'Sydney CBD',
    'Sydney',
    'Platform operator for seed data.',
    null,
    '{exploring}'::connection_intent[],
    now(),
    now()
  )
on conflict (email) do nothing;

insert into profiles (
  auth_subject,
  role,
  email,
  display_name,
  age,
  gender,
  suburb,
  city,
  bio,
  photo_url,
  connection_intents,
  email_verified_at,
  photo_verified_at
) values
  (
    'seed:customer:lena',
    'attendee',
    'lena@click.local',
    'Lena Ortiz',
    32,
    'woman',
    'Potts Point',
    'Sydney',
    'Likes small restaurant tables, friendly hosts, and plans where nobody has to coordinate a group chat.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:grace',
    'attendee',
    'grace@click.local',
    'Grace Liu',
    28,
    'woman',
    'Haymarket',
    'Sydney',
    'Always knows a good noodle shop and wants more weeknight dinner plans close to the city.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:marcus',
    'attendee',
    'marcus@click.local',
    'Marcus Bell',
    35,
    'man',
    'Enmore',
    'Sydney',
    'Usually at small gigs, record shops, and late sets, but wants to stop arriving alone.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:elise',
    'attendee',
    'elise@click.local',
    'Elise Grant',
    30,
    'woman',
    'Bronte',
    'Sydney',
    'Prefers early starts, gentle movement, tea after class, and people who do not rush connection.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:mina',
    'attendee',
    'mina@click.local',
    'Mina Patel',
    37,
    'woman',
    'Sydney CBD',
    'Sydney',
    'Building a services business and looking for candid breakfast chats with other women doing the same.',
    null,
    '{networking,friendship}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:samira',
    'attendee',
    'samira@click.local',
    'Samira Haddad',
    33,
    'woman',
    'Kings Cross',
    'Sydney',
    'Likes useful volunteering, meal prep nights, and meeting people while doing something tangible.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:ruby',
    'attendee',
    'ruby@click.local',
    'Ruby Walsh',
    27,
    'woman',
    'Alexandria',
    'Sydney',
    'Wants pottery, sketchbooks, snacks, and people who are happy making imperfect things together.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:oscar',
    'attendee',
    'oscar@click.local',
    'Oscar Finch',
    31,
    'man',
    'Glebe',
    'Sydney',
    'Knows random facts, likes friendly competition, and wants a regular Sunday team.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:hannah',
    'attendee',
    'hannah@click.local',
    'Hannah Reid',
    34,
    'woman',
    'North Sydney',
    'Sydney',
    'Reads on the train, likes parks, and prefers softer events where silence is not awkward.',
    null,
    '{friendship}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:ben',
    'attendee',
    'ben@click.local',
    'Ben Archer',
    36,
    'man',
    'Manly',
    'Sydney',
    'Usually near the water, keen for low-admin outdoor plans and ferry-friendly weekend mates.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:asha',
    'attendee',
    'asha@click.local',
    'Asha Kumar',
    29,
    'woman',
    'Parramatta',
    'Sydney',
    'Wants a west-side circle for dinners, walks, and plans that do not always mean crossing town.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:leo',
    'attendee',
    'leo@click.local',
    'Leo Martin',
    26,
    'man',
    'Redfern',
    'Sydney',
    'Carries a camera most evenings and likes walking conversations with a creative prompt.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:nina',
    'attendee',
    'nina@click.local',
    'Nina Alvarez',
    33,
    'woman',
    'Coogee',
    'Sydney',
    'Likes ocean swimming, regular routines, and people who take safety seriously without making it intense.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:talia',
    'attendee',
    'talia@click.local',
    'Talia Brooks',
    30,
    'woman',
    'Bondi',
    'Sydney',
    'Runs for the post-run chat as much as the kilometres and likes mixed-pace groups.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  ),
  (
    'seed:customer:kai',
    'attendee',
    'kai@click.local',
    'Kai Wong',
    28,
    'non-binary',
    'Camperdown',
    'Sydney',
    'New to the inner west, owns too many tote bags, and wants useful local rituals.',
    null,
    '{friendship,exploring}'::connection_intent[],
    now(),
    now()
  )
on conflict (email) do nothing;

insert into merchant_profiles (
  profile_id,
  business_name,
  abn,
  website_url,
  contact_email,
  verification_status,
  stripe_connect_account_id
)
-- stripe_connect_account_id is seeded NULL: a fake `acct_*` id 404s when the
-- payout-onboarding flow calls accountLinks.create. NULL lets the flow mint a
-- real Connect account on first use.
select profile.id, merchant.business_name, merchant.abn, merchant.website_url, profile.email, 'approved', merchant.stripe_account::text
from (
  values
    ('theo@click.local', 'Inner West Fitness Mates', '11 111 111 111', 'https://example.com/fitness', null),
    ('amelia@click.local', 'Real Conversations Sydney', '22 222 222 222', 'https://example.com/conversations', null),
    ('noah@click.local', 'Ordinary People Making Things', '33 333 333 333', 'https://example.com/creative', null),
    ('priya@click.local', 'Sydney Career Switchers', '44 444 444 444', 'https://example.com/career', null)
) as merchant(email, business_name, abn, website_url, stripe_account)
join profiles profile on profile.email = merchant.email
on conflict (profile_id) do nothing;

with host_profiles as (
  select
    profile.id as profile_id,
    profile.display_name,
    merchant.id as merchant_id,
    merchant.business_name
  from profiles profile
  left join merchant_profiles merchant on merchant.profile_id = profile.id
),
seed_events as (
  select *
  from (
    values
      (
        'new-friends-barangaroo',
        'New Friends Picnic at Bondi',
        'A hosted picnic for people who want easy conversation, shared snacks, and familiar faces for the next event.',
        'maya@click.local',
        null::text,
        'Sydney First-Timers Social Club',
        'Maya Chen',
        'Social',
        'featured'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-05-08 18:30:00+10'::timestamptz,
        '2026-05-08 20:30:00+10'::timestamptz,
        'Bondi Pavilion',
        'Queen Elizabeth Dr, Bondi Beach NSW 2026',
        'Bondi Beach',
        -33.891300::numeric,
        151.274400::numeric,
        0,
        60,
        '/media/open-yoga.jpg',
        'People gathering outdoors in a relaxed group class',
        'Make two familiar faces before the next weekend.',
        '4 people you might Click with are already going.'
      ),
      (
        'crossfit-coffee',
        'CrossFit Skills and Coffee Crew',
        'Technique-focused partner drills, scalable workouts, and post-session coffee for people who want consistency without gym cliques.',
        'theo@click.local',
        'Inner West Fitness Mates',
        'Inner West Fitness Mates',
        'Theo Morgan',
        'Fitness',
        'live'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-05-09 08:00:00+10'::timestamptz,
        '2026-05-09 09:30:00+10'::timestamptz,
        'CrossFit Marrickville',
        '9 Sydenham Rd, Marrickville NSW 2204',
        'Marrickville',
        -33.910000::numeric,
        151.156500::numeric,
        1200,
        32,
        '/media/yoga.jpg',
        'People training together in a group fitness session',
        'Find a fitness partner for a four-week streak.',
        'Popular with people building a four-week fitness streak.'
      ),
      (
        'slow-dating-six',
        'Slow Dating: Dinner Tables of Six',
        'Hosted dinner tables where singles meet through small-group conversation first, with private mutual interest after the event.',
        'amelia@click.local',
        'Real Conversations Sydney',
        'Real Conversations Sydney',
        'Amelia Hart',
        'Relationships',
        'waitlist'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-05-14 19:00:00+10'::timestamptz,
        '2026-05-14 21:00:00+10'::timestamptz,
        'Petersham Bowling Club',
        '77 Brighton St, Petersham NSW 2049',
        'Petersham',
        -33.895400::numeric,
        151.154100::numeric,
        2900,
        42,
        '/media/networking.jpg',
        'People talking at a warm hosted dinner event',
        'Meet people through conversation before matching.',
        'Mostly relationship-minded guests who prefer small tables.'
      ),
      (
        'restaurant-table-eight',
        'Restaurant Meetup: Table for Eight',
        'A hosted restaurant table for people who want dinner plans without the awkward group-chat setup. Arrive solo, sit with eight, and let the host open the first conversation.',
        'amelia@click.local',
        'Real Conversations Sydney',
        'Sydney Table Friends',
        'Lena Ortiz',
        'Food',
        'live'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-05-15 19:00:00+10'::timestamptz,
        '2026-05-15 21:00:00+10'::timestamptz,
        'North Bondi Fish',
        '120 Ramsgate Ave, North Bondi NSW 2026',
        'North Bondi',
        -33.888800::numeric,
        151.281400::numeric,
        3800,
        8,
        '/media/networking.jpg',
        'People sharing food and conversation at a restaurant table',
        'Make dinner feel like the easiest first plan with new people.',
        'Only two seats left at a small table designed for easy conversation.'
      ),
      (
        'ordinary-creatives',
        'Creative Brunch for Ordinary People',
        'A no-status brunch for writers, designers, builders, makers, and anyone who wants a recurring community around doing real things.',
        'noah@click.local',
        'Ordinary People Making Things',
        'Ordinary People Making Things',
        'Noah Singh',
        'Creative',
        'featured'::event_status,
        'external'::booking_model,
        'https://example.com/book/creative-brunch',
        '2026-05-17 10:30:00+10'::timestamptz,
        '2026-05-17 12:30:00+10'::timestamptz,
        'The Courthouse Hotel',
        '202 Australia St, Newtown NSW 2042',
        'Newtown',
        -33.897600::numeric,
        151.179300::numeric,
        1800,
        70,
        '/media/concert.jpg',
        'Crowd at a warm local music and creative event',
        'Turn a hobby into a recurring group.',
        'Strong overlap with makers, writers, and new locals.'
      ),
      (
        'career-walk',
        'Career Change Walk and Talk',
        'A walking meetup for people changing careers, building confidence, and looking for peers rather than formal networking.',
        'priya@click.local',
        'Sydney Career Switchers',
        'Sydney Career Switchers',
        'Priya Nair',
        'Career',
        'live'::event_status,
        'external'::booking_model,
        'https://example.com/book/career-walk',
        '2026-05-20 18:00:00+10'::timestamptz,
        '2026-05-20 19:30:00+10'::timestamptz,
        'Bay Run, King George Park',
        'Charles St, Lilyfield NSW 2040',
        'Lilyfield',
        -33.868100::numeric,
        151.160300::numeric,
        0,
        45,
        '/media/networking.jpg',
        'People talking at a community meetup',
        'Meet peers who understand the same career transition.',
        'Good fit for people rebuilding confidence around work.'
      ),
      (
        'dog-park-cleanup',
        'Dog Park Coffee and Cleanup',
        'A light volunteer morning for pet owners, locals, and people who want a natural reason to talk while doing something useful.',
        'maya@click.local',
        null::text,
        'Inner City Community Mates',
        'Jules Park',
        'Community',
        'locked'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-05-23 09:00:00+10'::timestamptz,
        '2026-05-23 11:00:00+10'::timestamptz,
        'Camperdown Memorial Rest Park',
        'Federation Rd, Newtown NSW 2042',
        'Camperdown',
        -33.890200::numeric,
        151.178800::numeric,
        0,
        36,
        '/media/open-yoga.jpg',
        'Outdoor community group meeting in a park',
        'Meet locals through a useful shared ritual.',
        'Popular with pet owners and people new to Camperdown.'
      ),
      (
        'bondi-coastal-run',
        'Bondi Coastal Run and Smoothies',
        'A conversational coastal run for mixed paces, followed by smoothies and an easy stretch on the grass.',
        'theo@click.local',
        null::text,
        'Eastern Beaches Run Club',
        'Talia Brooks',
        'Fitness',
        'live'::event_status,
        'external'::booking_model,
        'https://example.com/book/bondi-run',
        '2026-05-24 07:30:00+10'::timestamptz,
        '2026-05-24 09:00:00+10'::timestamptz,
        'Bondi Icebergs Club',
        '1 Notts Ave, Bondi Beach NSW 2026',
        'Bondi Beach',
        -33.891500::numeric,
        151.276700::numeric,
        0,
        50,
        '/media/yoga.jpg',
        'People stretching before an outdoor fitness meetup',
        'Find a familiar face for weekend movement.',
        'Popular with people who want fitness without a competitive vibe.'
      ),
      (
        'haymarket-dumpling-night',
        'Dumpling Night for New Locals',
        'A small shared-table dinner where the host handles ordering, introductions, and keeping the conversation moving.',
        'amelia@click.local',
        null::text,
        'Sydney Table Friends',
        'Grace Liu',
        'Food',
        'featured'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-05-25 18:45:00+10'::timestamptz,
        '2026-05-25 20:45:00+10'::timestamptz,
        'Din Tai Fung, Westfield Bondi Junction',
        '500 Oxford St, Bondi Junction NSW 2022',
        'Bondi Junction',
        -33.891500::numeric,
        151.250300::numeric,
        2200,
        18,
        '/media/networking.jpg',
        'People sharing casual food at a group table',
        'Turn a simple dinner into a first Sydney circle.',
        'A strong fit for people who want dinner plans after work.'
      ),
      (
        'enmore-live-jazz',
        'Live Jazz at Enmore Back Room',
        'A hosted live jazz night for people who like music but do not want to arrive alone or force small talk.',
        'noah@click.local',
        null::text,
        'Late Set Listeners',
        'Marcus Bell',
        'Creative',
        'live'::event_status,
        'external'::booking_model,
        'https://example.com/book/enmore-jazz',
        '2026-05-26 20:00:00+10'::timestamptz,
        '2026-05-26 22:00:00+10'::timestamptz,
        'Enmore Theatre',
        '130 Enmore Rd, Enmore NSW 2042',
        'Enmore',
        -33.897700::numeric,
        151.174000::numeric,
        1800,
        40,
        '/media/concert.jpg',
        'Crowd listening to a small live music performance',
        'Make live music feel like a shared plan, not a solo errand.',
        'Great overlap with music lovers and quieter creative people.'
      ),
      (
        'bronte-sunrise-yoga',
        'Bronte Sunrise Yoga and Tea',
        'Gentle yoga, warm tea, and a short intro circle before work. Designed for people easing back into social mornings.',
        'theo@click.local',
        null::text,
        'Soft Start Sydney',
        'Elise Grant',
        'Fitness',
        'live'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-05-27 06:30:00+10'::timestamptz,
        '2026-05-27 07:45:00+10'::timestamptz,
        'Bronte Beach Park',
        'Bronte Rd, Bronte NSW 2024',
        'Bronte',
        -33.903800::numeric,
        151.263500::numeric,
        1500,
        30,
        '/media/yoga.jpg',
        'Outdoor group yoga session on grass',
        'Create a calm first meeting before the day gets busy.',
        'Most people come solo and leave with one familiar name.'
      ),
      (
        'women-founder-breakfast',
        'Women Founders Breakfast Circle',
        'A practical founder breakfast for women building, freelancing, switching lanes, or wanting a sharper peer circle.',
        'priya@click.local',
        null::text,
        'Sydney Career Switchers',
        'Mina Patel',
        'Career',
        'waitlist'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-05-28 08:00:00+10'::timestamptz,
        '2026-05-28 09:30:00+10'::timestamptz,
        'The Grounds of Alexandria',
        '7A/2 Huntley St, Alexandria NSW 2015',
        'Alexandria',
        -33.910900::numeric,
        151.194100::numeric,
        3200,
        24,
        '/media/networking.jpg',
        'People networking over breakfast',
        'Make professional support feel candid and useful.',
        'Nearly full with people comparing real work problems, not pitches.'
      ),
      (
        'kings-cross-community-kitchen',
        'Community Kitchen Prep Night',
        'Prep meals with a small volunteer crew, then share tea afterward. A useful way to meet people without performative networking.',
        'maya@click.local',
        null::text,
        'Eastern Beaches Community Mates',
        'Samira Haddad',
        'Community',
        'live'::event_status,
        'external'::booking_model,
        'https://example.com/book/community-kitchen',
        '2026-05-29 17:30:00+10'::timestamptz,
        '2026-05-29 19:30:00+10'::timestamptz,
        'Waverley Community Centre',
        '5 Henrietta St, Waverley NSW 2024',
        'Waverley',
        -33.902000::numeric,
        151.252000::numeric,
        0,
        35,
        '/media/open-yoga.jpg',
        'Community volunteers gathering outdoors',
        'Meet good people through a practical shared task.',
        'Good fit for people who prefer doing something useful while talking.'
      ),
      (
        'alexandria-pottery-night',
        'After-Work Pottery Night',
        'Beginner-friendly pottery with hosted table prompts, a snack break, and zero expectation that the bowl turns out straight.',
        'noah@click.local',
        null::text,
        'Ordinary People Making Things',
        'Ruby Walsh',
        'Creative',
        'featured'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-05-30 16:00:00+10'::timestamptz,
        '2026-05-30 18:00:00+10'::timestamptz,
        'Clay Sydney Studio',
        '8 Burrows Rd, Alexandria NSW 2015',
        'Alexandria',
        -33.909500::numeric,
        151.194800::numeric,
        4500,
        22,
        '/media/concert.jpg',
        'Creative group event with warm lighting',
        'Give people a shared object to laugh about and remember.',
        'A favourite for people who want a task to make conversation easier.'
      ),
      (
        'glebe-trivia-teamup',
        'Glebe Trivia Team-Up',
        'Arrive solo and get placed on a friendly trivia team. The host rotates teams after round two so nobody is stuck.',
        'maya@click.local',
        null::text,
        'Pub Quiz People',
        'Oscar Finch',
        'Social',
        'live'::event_status,
        'external'::booking_model,
        'https://example.com/book/glebe-trivia',
        '2026-05-31 18:00:00+10'::timestamptz,
        '2026-05-31 20:00:00+10'::timestamptz,
        'The Toxteth Hotel',
        '345 Glebe Point Rd, Glebe NSW 2037',
        'Glebe',
        -33.880000::numeric,
        151.185600::numeric,
        800,
        48,
        '/media/networking.jpg',
        'People talking at a local social event',
        'Make a group game do the first-conversation work.',
        'Works well for people who want instant team energy.'
      ),
      (
        'north-sydney-book-swap',
        'Sydney Park Book Swap Picnic',
        'Bring one book, swap stories about it, and join a low-key picnic for people who prefer quieter social plans.',
        'maya@click.local',
        null::text,
        'Quiet Pages Club',
        'Hannah Reid',
        'Social',
        'live'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-06-02 18:00:00+10'::timestamptz,
        '2026-06-02 20:00:00+10'::timestamptz,
        'Sydney Park',
        '405 Sydney Park Rd, St Peters NSW 2044',
        'St Peters',
        -33.909500::numeric,
        151.184200::numeric,
        0,
        28,
        '/media/open-yoga.jpg',
        'Relaxed outdoor social group sitting in a park',
        'Let a favourite book introduce people for you.',
        'Designed for people who like a softer room and a reason to talk.'
      ),
      (
        'manly-snorkel-walk',
        'Clovelly Snorkel Walk and Chips',
        'A calm snorkel and coastal walk for confident swimmers, ending with hot chips on the grass.',
        'theo@click.local',
        null::text,
        'Eastern Beaches Weekend Crew',
        'Ben Archer',
        'Fitness',
        'live'::event_status,
        'external'::booking_model,
        'https://example.com/book/manly-snorkel',
        '2026-06-06 10:00:00+10'::timestamptz,
        '2026-06-06 13:00:00+10'::timestamptz,
        'Clovelly Beach',
        'Clovelly Rd, Clovelly NSW 2031',
        'Clovelly',
        -33.914100::numeric,
        151.267800::numeric,
        1000,
        26,
        '/media/yoga.jpg',
        'Outdoor group preparing for an active meetup',
        'Turn an outdoor plan into a repeat weekend crew.',
        'Best for people who want a whole Saturday plan with a small crew.'
      ),
      (
        'parramatta-newcomers-dinner',
        'Leichhardt Newcomers Dinner',
        'A small-table dinner for people in Western Sydney who want local friends without travelling into the CBD every time.',
        'amelia@click.local',
        null::text,
        'Inner West Welcome Table',
        'Asha Kumar',
        'Food',
        'featured'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-06-07 18:30:00+10'::timestamptz,
        '2026-06-07 20:30:00+10'::timestamptz,
        'Bar Italia',
        '169-171 Norton St, Leichhardt NSW 2040',
        'Leichhardt',
        -33.883500::numeric,
        151.157300::numeric,
        3400,
        14,
        '/media/networking.jpg',
        'People meeting over dinner at a warm group table',
        'Help Western Sydney locals meet closer to home.',
        'Strong fit for west-side locals building a nearby circle.'
      ),
      (
        'redfern-photo-walk',
        'Redfern Photo Walk and Coffee',
        'A guided street-photo loop with simple prompts, paired walking, and coffee after for anyone using a phone or camera.',
        'noah@click.local',
        null::text,
        'Street Frames Sydney',
        'Leo Martin',
        'Creative',
        'live'::event_status,
        'external'::booking_model,
        'https://example.com/book/redfern-photo',
        '2026-06-09 17:45:00+10'::timestamptz,
        '2026-06-09 19:30:00+10'::timestamptz,
        'Redfern Station',
        'Lawson St, Redfern NSW 2016',
        'Redfern',
        -33.891700::numeric,
        151.198900::numeric,
        0,
        32,
        '/media/concert.jpg',
        'Creative community group at an evening event',
        'Use photography prompts to make conversation natural.',
        'Great first event for people who like walking with a shared focus.'
      ),
      (
        'coogee-ocean-swim',
        'Coogee Ocean Swim Buddies',
        'A beginner-aware ocean swim meetup with pairs, safety check-ins, and coffee for anyone wanting a regular swim buddy.',
        'theo@click.local',
        null::text,
        'Eastern Beaches Run Club',
        'Nina Alvarez',
        'Fitness',
        'locked'::event_status,
        'click_managed'::booking_model,
        null::text,
        '2026-06-10 07:00:00+10'::timestamptz,
        '2026-06-10 08:30:00+10'::timestamptz,
        'Coogee Surf Life Saving Club',
        'Goldstein Reserve, Beach St, Coogee NSW 2034',
        'Coogee',
        -33.922500::numeric,
        151.257900::numeric,
        0,
        24,
        '/media/yoga.jpg',
        'Outdoor fitness group by the water',
        'Make regular ocean swimming feel social and safer.',
        'Good fit for confident swimmers who still prefer not to go alone.'
      )
  ) as event_seed(
    slug,
    title,
    description,
    host_email,
    merchant_business_name,
    group_name,
    host_name,
    category,
    status,
    booking_model,
    external_booking_url,
    starts_at,
    ends_at,
    location_name,
    address,
    suburb,
    latitude,
    longitude,
    price_cents,
    capacity,
    image_url,
    image_alt,
    relationship_goal,
    fomo
  )
)
insert into events (
  slug,
  title,
  description,
  host_profile_id,
  merchant_profile_id,
  group_name,
  host_name,
  category,
  status,
  booking_model,
  external_booking_url,
  starts_at,
  ends_at,
  location_name,
  address,
  suburb,
  latitude,
  longitude,
  price_cents,
  capacity,
  image_url,
  image_alt,
  relationship_goal,
  fomo
)
select
  seed_events.slug,
  seed_events.title,
  seed_events.description,
  host.profile_id,
  host.merchant_id,
  seed_events.group_name,
  seed_events.host_name,
  seed_events.category,
  seed_events.status,
  seed_events.booking_model,
  seed_events.external_booking_url,
  seed_events.starts_at,
  seed_events.ends_at,
  seed_events.location_name,
  seed_events.address,
  seed_events.suburb,
  seed_events.latitude,
  seed_events.longitude,
  seed_events.price_cents,
  seed_events.capacity,
  seed_events.image_url,
  seed_events.image_alt,
  seed_events.relationship_goal,
  seed_events.fomo
from seed_events
join profiles host_profile on host_profile.email = seed_events.host_email
left join host_profiles host on host.profile_id = host_profile.id
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  status = excluded.status,
  booking_model = excluded.booking_model,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  capacity = excluded.capacity,
  updated_at = now();

with event_tag_seed as (
  select *
  from (
    values
      ('new-friends-barangaroo', 'friends'),
      ('new-friends-barangaroo', 'new-to-town'),
      ('new-friends-barangaroo', 'low-pressure'),
      ('new-friends-barangaroo', 'weekend'),
      ('crossfit-coffee', 'crossfit'),
      ('crossfit-coffee', 'fitness'),
      ('crossfit-coffee', 'accountability'),
      ('ordinary-creatives', 'creative'),
      ('ordinary-creatives', 'brunch'),
      ('ordinary-creatives', 'friends'),
      ('slow-dating-six', 'dating'),
      ('slow-dating-six', 'relationships'),
      ('slow-dating-six', 'low-pressure'),
      ('restaurant-table-eight', 'restaurant'),
      ('restaurant-table-eight', 'dinner'),
      ('restaurant-table-eight', 'food'),
      ('restaurant-table-eight', 'low-pressure'),
      ('bondi-coastal-run', 'running'),
      ('bondi-coastal-run', 'fitness'),
      ('bondi-coastal-run', 'morning'),
      ('haymarket-dumpling-night', 'dumplings'),
      ('haymarket-dumpling-night', 'dinner'),
      ('haymarket-dumpling-night', 'food'),
      ('haymarket-dumpling-night', 'new-to-town'),
      ('enmore-live-jazz', 'live-music'),
      ('enmore-live-jazz', 'jazz'),
      ('enmore-live-jazz', 'creative'),
      ('bronte-sunrise-yoga', 'yoga'),
      ('bronte-sunrise-yoga', 'wellness'),
      ('bronte-sunrise-yoga', 'morning'),
      ('women-founder-breakfast', 'career-change'),
      ('women-founder-breakfast', 'founders'),
      ('women-founder-breakfast', 'women'),
      ('kings-cross-community-kitchen', 'volunteering'),
      ('kings-cross-community-kitchen', 'community'),
      ('kings-cross-community-kitchen', 'food'),
      ('alexandria-pottery-night', 'pottery'),
      ('alexandria-pottery-night', 'creative'),
      ('alexandria-pottery-night', 'weekend'),
      ('glebe-trivia-teamup', 'games'),
      ('glebe-trivia-teamup', 'friends'),
      ('north-sydney-book-swap', 'books'),
      ('north-sydney-book-swap', 'quiet'),
      ('north-sydney-book-swap', 'friends'),
      ('manly-snorkel-walk', 'outdoors'),
      ('manly-snorkel-walk', 'fitness'),
      ('manly-snorkel-walk', 'weekend'),
      ('parramatta-newcomers-dinner', 'dinner'),
      ('parramatta-newcomers-dinner', 'food'),
      ('parramatta-newcomers-dinner', 'new-to-town'),
      ('redfern-photo-walk', 'photography'),
      ('redfern-photo-walk', 'creative'),
      ('redfern-photo-walk', 'confidence'),
      ('coogee-ocean-swim', 'swimming'),
      ('coogee-ocean-swim', 'fitness'),
      ('coogee-ocean-swim', 'morning'),
      ('career-walk', 'career-change'),
      ('career-walk', 'confidence'),
      ('dog-park-cleanup', 'pets'),
      ('dog-park-cleanup', 'volunteering'),
      ('dog-park-cleanup', 'friends')
  ) as values_list(event_slug, tag_slug)
)
insert into event_tags (event_id, tag_id)
select event.id, tag.id
from event_tag_seed
join events event on event.slug = event_tag_seed.event_slug
join tags tag on tag.slug = event_tag_seed.tag_slug
on conflict do nothing;

insert into profiles (
  auth_subject,
  role,
  email,
  display_name,
  suburb,
  city,
  bio,
  connection_intents,
  email_verified_at,
  photo_verified_at
)
select
  'seed:attendee:' || series.index,
  'attendee',
  ('attendee+' || series.index || '@click.local')::citext,
  'Click Member ' || series.index,
  case series.index % 6
    when 0 then 'Barangaroo'
    when 1 then 'Marrickville'
    when 2 then 'Surry Hills'
    when 3 then 'Newtown'
    when 4 then 'The Rocks'
    else 'Camperdown'
  end,
  'Sydney',
  'Seed attendee used to populate event capacity and FOMO examples.',
  '{friendship,exploring}'::connection_intent[],
  now(),
  now()
from generate_series(1, 70) as series(index)
on conflict (email) do nothing;

with attendance_targets as (
  select *
  from (
    values
      ('new-friends-barangaroo', 47),
      ('crossfit-coffee', 24),
      ('slow-dating-six', 40),
      ('restaurant-table-eight', 6),
      ('ordinary-creatives', 53),
      ('career-walk', 31),
      ('dog-park-cleanup', 18),
      ('bondi-coastal-run', 34),
      ('haymarket-dumpling-night', 14),
      ('enmore-live-jazz', 28),
      ('bronte-sunrise-yoga', 22),
      ('women-founder-breakfast', 19),
      ('kings-cross-community-kitchen', 26),
      ('alexandria-pottery-night', 18),
      ('glebe-trivia-teamup', 41),
      ('north-sydney-book-swap', 17),
      ('manly-snorkel-walk', 21),
      ('parramatta-newcomers-dinner', 10),
      ('redfern-photo-walk', 23),
      ('coogee-ocean-swim', 16)
  ) as target(event_slug, attendee_count)
),
expanded_attendance as (
  select
    target.event_slug,
    series.index
  from attendance_targets target
  cross join lateral generate_series(1, target.attendee_count) as series(index)
)
insert into event_attendees (event_id, profile_id, status)
select event.id, profile.id, 'confirmed'
from expanded_attendance attendance
join events event on event.slug = attendance.event_slug
join profiles profile on profile.email = ('attendee+' || attendance.index || '@click.local')::citext
on conflict (event_id, profile_id) do nothing;

insert into notifications (profile_id, channel, title, body, action_url)
select profile.id, 'in_app', 'Welcome to Click', 'Your event-first dashboard is ready.', '/dashboard'
from profiles profile
where profile.email in ('maya@click.local', 'theo@click.local', 'amelia@click.local')
on conflict do nothing;

commit;
