import { AdminEventQueue } from "@/components/admin-event-queue";
import { AdminMembersTable } from "@/components/admin-members-table";
import { AdminMerchantsTable } from "@/components/admin-merchants-table";
import { AdminWorkspace } from "@/components/admin-workspace";
import { InfoCard, MetricCard, PageHero, Pill, SectionIntro } from "@/components/click-ui";
import {
  adminModules,
  interestTagCategories,
  securityRows,
} from "@/lib/click-data";
import {
  getAdminAuditLog,
  getAdminEvents,
  getAdminMembers,
  getAdminMerchants,
  getAdminMetrics,
} from "@/lib/event-repository";

export const metadata = {
  title: "Admin Portal | Click",
  description: "Click admin portal for moderation, tag governance, security, and analytics.",
};

const dateFormatter = new Intl.DateTimeFormat("en-AU", {
  day: "numeric",
  month: "short",
  hour: "numeric",
  minute: "2-digit",
});

function formatActionLabel(action: string) {
  return action.replace(/_/g, " ");
}

function formatMetadata(metadata: Record<string, unknown>) {
  const entries = Object.entries(metadata);
  if (entries.length === 0) return "—";
  return entries
    .map(([key, value]) => `${key}: ${typeof value === "string" ? value : JSON.stringify(value)}`)
    .join(" · ");
}

export default async function AdminPage() {
  const [events, members, merchants, audit] = await Promise.all([
    getAdminEvents(),
    getAdminMembers(),
    getAdminMerchants(),
    getAdminAuditLog(),
  ]);
  const metrics = await getAdminMetrics(events);
  const pendingCount = events.filter((event) => event.status === "Pending").length;

  const overviewPanel = (
    <div className="space-y-12 py-10">
      <SectionIntro
        eyebrow="Operations"
        title="Admin work is approvals, governance, and proof."
        body="Every sensitive action should require a confirmation step and write to an audit trail."
      />

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <MetricCard label="Members" value={metrics.totalMembers.toLocaleString()} tone="cream" />
        <MetricCard label="New this week" value={metrics.newMembersThisWeek.toLocaleString()} tone="peach" />
        <MetricCard label="Pending events" value={metrics.pendingEvents.toLocaleString()} tone="rose" />
        <MetricCard label="Pending merchants" value={metrics.pendingMerchants.toLocaleString()} tone="ink" />
        <MetricCard label="Total events" value={metrics.totalEvents.toLocaleString()} tone="peach" />
        <MetricCard label="Confirmed RSVPs" value={metrics.confirmedRsvps.toLocaleString()} tone="cream" />
        <MetricCard label="Merchants" value={metrics.totalMerchants.toLocaleString()} tone="rose" />
        <MetricCard label="Mutual Clicks" value={metrics.mutualClicks.toLocaleString()} tone="ink" />
      </div>

      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
        {adminModules.map(([title, body], index) => (
          <InfoCard
            key={title}
            title={title}
            body={body}
            accent={index === 4 ? "rose" : index === 5 ? "ink" : "peach"}
          />
        ))}
      </div>
    </div>
  );

  const membersPanel = (
    <div className="space-y-8 py-10">
      <SectionIntro
        eyebrow="Members"
        title="Profiles, intent, and verification at a glance."
        body="Filter by role, search by name, email, or suburb, and see who is actively saving or RSVP-ing."
      />
      <AdminMembersTable members={members} />
    </div>
  );

  const eventsPanel = (
    <div className="space-y-8 py-10">
      <SectionIntro
        eyebrow="Events"
        title="Review events before they shape the marketplace."
        body="Tag accuracy, duplicates, photos, capacity, booking model, and location claims live here. Approving an event writes to the audit log."
      />
      <AdminEventQueue events={events} />
    </div>
  );

  const merchantsPanel = (
    <div className="space-y-8 py-10">
      <SectionIntro
        eyebrow="Merchants"
        title="Verification, contact info, and event volume."
        body="Approve hosts after ABN, contact, and website checks. Pending merchants cannot launch Click-managed bookings."
      />
      <AdminMerchantsTable merchants={merchants} />
    </div>
  );

  const tagsPanel = (
    <div className="space-y-8 py-10">
      <SectionIntro
        eyebrow="Tag governance"
        title="Interest Tags are product infrastructure."
        body="Life Tags are generated by the system. Interest Tags are curated by admins to prevent duplicates and keep discovery quality high."
      />
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {interestTagCategories.slice(0, 9).map(([category, ...tags]) => (
          <article
            key={category}
            className="rounded-2xl border-2 border-[color:var(--line)] bg-[color:var(--champagne)] p-5 hard-shadow-sm"
          >
            <div className="flex items-center justify-between gap-3">
              <h3 className="font-display text-3xl font-light leading-none text-[color:var(--ink)]">
                {category}
              </h3>
              <Pill tone="peach">{tags.length} tags</Pill>
            </div>
            <p className="mt-3 text-sm font-medium leading-6 text-[color:var(--mauve)]">
              Merge duplicates, archive stale labels, cascade updates to linked users, merchants, and events.
            </p>
            <div className="mt-4 flex flex-wrap gap-1.5">
              {tags.slice(0, 6).map((tag) => (
                <span
                  key={tag}
                  className="rounded-full border border-[color:var(--line)] bg-[color:var(--cream)] px-2.5 py-0.5 text-[0.65rem] font-bold uppercase tracking-wider text-[color:var(--ink)]"
                >
                  {tag}
                </span>
              ))}
              {tags.length > 6 ? (
                <span className="text-[0.65rem] font-bold uppercase tracking-wider text-[color:var(--mauve)]">
                  +{tags.length - 6} more
                </span>
              ) : null}
            </div>
          </article>
        ))}
      </div>
    </div>
  );

  const auditPanel = (
    <div className="space-y-8 py-10">
      <SectionIntro
        eyebrow="Audit log"
        title="Every sensitive action leaves a trace."
        body="Approvals, verifications, tag changes, financial edits, and moderation actions are recorded with actor, target, and time."
      />
      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
        {securityRows.map(([title, body], index) => (
          <InfoCard
            key={title}
            title={title}
            body={body}
            accent={index === 0 ? "rose" : "peach"}
          />
        ))}
      </div>

      <div className="overflow-hidden rounded-2xl border-2 border-[color:var(--line)] bg-[color:var(--champagne)] hard-shadow-sm">
        <div className="hidden grid-cols-[0.9fr_1fr_1.4fr_0.7fr] gap-4 bg-[color:var(--surface-deep)] px-5 py-3 text-xs font-black uppercase tracking-[0.14em] text-[color:var(--on-deep)] md:grid">
          <span>Action</span>
          <span>Actor</span>
          <span>Detail</span>
          <span>When</span>
        </div>
        {audit.length === 0 ? (
          <p className="px-5 py-8 text-center text-sm font-bold text-[color:var(--mauve)]">
            No admin actions logged yet.
          </p>
        ) : (
          audit.map((entry) => (
            <div
              key={entry.id}
              className="grid gap-2 border-b border-[color:var(--line)] px-5 py-4 text-sm font-medium text-[color:var(--mauve)] last:border-0 md:grid-cols-[0.9fr_1fr_1.4fr_0.7fr] md:items-center"
            >
              <span className="font-black uppercase tracking-wider text-[color:var(--ink)]">
                {formatActionLabel(entry.action)}
              </span>
              <span>{entry.actorName ?? "System"}</span>
              <span className="break-words text-xs">{formatMetadata(entry.metadata)}</span>
              <span className="text-xs font-bold uppercase tracking-wider">
                {dateFormatter.format(new Date(entry.createdAt))}
              </span>
            </div>
          ))
        )}
      </div>
    </div>
  );

  return (
    <main className="min-h-screen bg-[color:var(--champagne)] text-[color:var(--ink)]">
      <PageHero
        eyebrow="Admin portal"
        title="Keep the room worth entering."
        body="Merchant approval, event moderation, member oversight, tag governance, audit logs, and payment review — all in one workspace."
      >
        <div className="grid grid-cols-2 gap-3">
          <MetricCard label="Members" value={metrics.totalMembers.toLocaleString()} tone="cream" />
          <MetricCard label="Merchants" value={metrics.totalMerchants.toLocaleString()} tone="peach" />
          <MetricCard label="Events" value={events.length.toString()} tone="rose" />
          <MetricCard label="Pending" value={pendingCount.toString()} tone="ink" />
        </div>
      </PageHero>

      <section className="bg-[color:var(--champagne)] px-4 pb-16 pt-4 sm:px-6">
        <AdminWorkspace
          counts={{
            members: members.length,
            events: events.length,
            merchants: merchants.length,
            audit: audit.length,
          }}
          panels={{
            overview: overviewPanel,
            members: membersPanel,
            events: eventsPanel,
            merchants: merchantsPanel,
            tags: tagsPanel,
            audit: auditPanel,
          }}
        />
      </section>
    </main>
  );
}
