import { AdminEventQueue } from "@/components/admin-event-queue";
import { InfoCard, MetricCard, PageHero, Pill, SectionIntro } from "@/components/click-ui";
import {
  adminModules,
  interestTagCategories,
  securityRows,
} from "@/lib/click-data";
import { getAdminEvents } from "@/lib/event-repository";

export const metadata = {
  title: "Admin Portal | Click",
  description: "Click admin portal for moderation, tag governance, security, and analytics.",
};

export default async function AdminPage() {
  const eventsForReview = await getAdminEvents();
  const pendingCount = eventsForReview.filter((event) => event.status === "Pending").length;

  return (
    <main className="min-h-screen bg-[color:var(--champagne)] text-[color:var(--ink)]">
      <PageHero
        eyebrow="Admin portal"
        title="Keep the room worth entering."
        body="The admin surface is operational: merchant approval, event moderation, user oversight, tag governance, audit logs, and payment review."
      >
          <div className="grid grid-cols-2 gap-3">
            <MetricCard label="Users" value="42k" tone="white" />
            <MetricCard label="Merchants" value="318" tone="aqua" />
            <MetricCard label="Events" value={eventsForReview.length.toString()} tone="pink" />
            <MetricCard label="Pending" value={pendingCount.toString()} tone="white" />
          </div>
        </PageHero>

      <section className="bg-[color:var(--champagne)] py-16">
        <div className="mx-auto max-w-7xl px-4 sm:px-6">
          <SectionIntro
            eyebrow="Operations"
            title="Admin work is approvals, governance, and proof."
            body="Every sensitive action should require a confirmation step and write to an audit trail."
          />

          <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
            {adminModules.map(([title, body], index) => (
              <InfoCard
                key={title}
                title={title}
                body={body}
                accent={index === 4 ? "pink" : index === 5 ? "mauve" : "aqua"}
              />
            ))}
          </div>
        </div>
      </section>

      <section className="bg-[color:var(--peach)] py-16">
        <div className="mx-auto max-w-7xl px-4 sm:px-6">
          <SectionIntro
            eyebrow="Moderation queue"
            title="Review events before they shape the marketplace."
            body="Admins verify tags, photos, duplicates, capacity, booking model, and location claims before an event goes live."
          />

          <AdminEventQueue events={eventsForReview} />
        </div>
      </section>

      <section className="bg-[color:var(--champagne)] py-16">
        <div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-[0.72fr_1.28fr]">
          <div>
            <SectionIntro
              eyebrow="Tag governance"
              title="Interest Tags are product infrastructure."
              body="Life Tags are generated by the system. Interest Tags are curated by admins to prevent duplicates and maintain discovery quality."
            />
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            {interestTagCategories.slice(0, 6).map(([category, ...tags]) => (
              <article
                key={category}
                className="rounded-lg border border-[color:var(--line)] bg-[color:var(--champagne)] p-5 shadow-sm"
              >
                <div className="flex items-center justify-between gap-3">
                  <h2 className="text-3xl font-black leading-none">
                    {category}
                  </h2>
                  <Pill tone="aqua">{tags.length} tags</Pill>
                </div>
                <p className="mt-3 text-sm font-bold leading-6 text-[color:var(--mauve)]">
                  Merge duplicates, archive stale labels, and cascade updates to linked
                  users, merchants, and events.
                </p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-[color:var(--surface-deep)] py-16 text-[color:var(--on-deep)]">
        <div className="mx-auto max-w-7xl px-4 sm:px-6">
          <SectionIntro
            eyebrow="Security and privacy"
            title="Trust controls should be visible to operators."
            body="The admin portal needs full oversight without casual overexposure. MFA, RLS, audit logs, and role scopes are not optional."
            invert
          />

          <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">
            {securityRows.map(([title, body], index) => (
              <InfoCard
                key={title}
                title={title}
                body={body}
                accent={index === 0 ? "pink" : "aqua"}
              />
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
